-- Migración cero — Fase 4 (plan §4.1/§4.2, decisión del operador 2026-08-23,
-- docs/migraciones/legado-consolidacion.md §-1): seed del catálogo de autorización.
-- Contenido ÍNTEGRO de 20260724010000_authz_fase2_seed.sql (idéntico al fixture ya usado por
-- el harness RLS, supabase/tests/local/40-fixture-rbac-catalog.sql) — sin este catálogo,
-- has_permission()/has_firmwide_assignment_visibility()/get_timesheet_approvers()/
-- get_engagement_team_candidates() quedan permanentemente rotas en cualquier reset.
--
-- =====================================================================
-- Roles & Permisos — FASE 1 (tanda 2): SEED de la matriz + role_key en user_roles
-- GENERADO automáticamente desde "Matriz de roles.md" (parser validado: 23/84/737, conteos por rol OK). No editar a mano.
-- Idempotente.
-- Conteos objetivo: 23 roles, 84 permisos, 737 concesiones.
-- =====================================================================

-- A) Roles (23)
insert into public.authorization_roles (role_key, label_key, display_order, is_system) values
  ('admin', 'authz.role.admin', 0, true),
  ('it_security_manager', 'authz.role.it_security_manager', 1, false),
  ('senior_partner', 'authz.role.senior_partner', 2, false),
  ('partner', 'authz.role.partner', 3, false),
  ('sqr', 'authz.role.sqr', 4, false),
  ('director', 'authz.role.director', 5, false),
  ('manager', 'authz.role.manager', 6, false),
  ('senior', 'authz.role.senior', 7, false),
  ('semisenior', 'authz.role.semisenior', 8, false),
  ('assistant', 'authz.role.assistant', 9, false),
  ('ita_manager', 'authz.role.ita_manager', 10, false),
  ('ita_senior', 'authz.role.ita_senior', 11, false),
  ('ita_assistant', 'authz.role.ita_assistant', 12, false),
  ('tax_manager', 'authz.role.tax_manager', 13, false),
  ('tax_senior', 'authz.role.tax_senior', 14, false),
  ('tax_assistant', 'authz.role.tax_assistant', 15, false),
  ('accounting_manager', 'authz.role.accounting_manager', 16, false),
  ('accounting_analyst', 'authz.role.accounting_analyst', 17, false),
  ('collections_analyst', 'authz.role.collections_analyst', 18, false),
  ('risk_partner', 'authz.role.risk_partner', 19, false),
  ('risk_supervisor', 'authz.role.risk_supervisor', 20, false),
  ('hr_manager', 'authz.role.hr_manager', 21, false),
  ('hr_analyst', 'authz.role.hr_analyst', 22, false)
on conflict (role_key) do nothing;

-- B) Permisos (84)
insert into public.authorization_permissions (permission_key, module_key, action_key, label_key, display_order) values
  ('staff.read', 'staff', 'read', 'authz.perm.staff.read', 0),
  ('staff.update', 'staff', 'update', 'authz.perm.staff.update', 1),
  ('staff.create', 'staff', 'create', 'authz.perm.staff.create', 2),
  ('staff.delete', 'staff', 'delete', 'authz.perm.staff.delete', 3),
  ('account.password.change', 'account', 'password.change', 'authz.perm.account.password.change', 4),
  ('industry.read', 'industry', 'read', 'authz.perm.industry.read', 5),
  ('industry.create', 'industry', 'create', 'authz.perm.industry.create', 6),
  ('industry.update', 'industry', 'update', 'authz.perm.industry.update', 7),
  ('industry.delete', 'industry', 'delete', 'authz.perm.industry.delete', 8),
  ('competency.read', 'competency', 'read', 'authz.perm.competency.read', 9),
  ('competency.create', 'competency', 'create', 'authz.perm.competency.create', 10),
  ('competency.update', 'competency', 'update', 'authz.perm.competency.update', 11),
  ('competency.delete', 'competency', 'delete', 'authz.perm.competency.delete', 12),
  ('category_rate.read', 'category_rate', 'read', 'authz.perm.category_rate.read', 13),
  ('category_rate.create', 'category_rate', 'create', 'authz.perm.category_rate.create', 14),
  ('category_rate.update', 'category_rate', 'update', 'authz.perm.category_rate.update', 15),
  ('category_rate.delete', 'category_rate', 'delete', 'authz.perm.category_rate.delete', 16),
  ('activity_code.read', 'activity_code', 'read', 'authz.perm.activity_code.read', 17),
  ('activity_code.create', 'activity_code', 'create', 'authz.perm.activity_code.create', 18),
  ('activity_code.update', 'activity_code', 'update', 'authz.perm.activity_code.update', 19),
  ('activity_code.delete', 'activity_code', 'delete', 'authz.perm.activity_code.delete', 20),
  ('expense_type.read', 'expense_type', 'read', 'authz.perm.expense_type.read', 21),
  ('expense_type.create', 'expense_type', 'create', 'authz.perm.expense_type.create', 22),
  ('expense_type.update', 'expense_type', 'update', 'authz.perm.expense_type.update', 23),
  ('expense_type.delete', 'expense_type', 'delete', 'authz.perm.expense_type.delete', 24),
  ('holiday.read', 'holiday', 'read', 'authz.perm.holiday.read', 25),
  ('holiday.create', 'holiday', 'create', 'authz.perm.holiday.create', 26),
  ('holiday.update', 'holiday', 'update', 'authz.perm.holiday.update', 27),
  ('holiday.delete', 'holiday', 'delete', 'authz.perm.holiday.delete', 28),
  ('user_role.read', 'user_role', 'read', 'authz.perm.user_role.read', 29),
  ('user_role.update', 'user_role', 'update', 'authz.perm.user_role.update', 30),
  ('staff_profile.create_from_account', 'user_role', 'staff_profile.create_from_account', 'authz.perm.staff_profile.create_from_account', 31),
  ('auth_account.delete', 'user_role', 'auth_account.delete', 'authz.perm.auth_account.delete', 32),
  ('global_settings.update', 'global_settings', 'update', 'authz.perm.global_settings.update', 33),
  ('dashboard.portfolio.read', 'dashboard', 'portfolio.read', 'authz.perm.dashboard.portfolio.read', 34),
  ('dashboard.engagement.read', 'dashboard', 'engagement.read', 'authz.perm.dashboard.engagement.read', 35),
  ('dashboard.personal.read', 'dashboard', 'personal.read', 'authz.perm.dashboard.personal.read', 36),
  ('dashboard.practice_financials.read', 'dashboard', 'practice_financials.read', 'authz.perm.dashboard.practice_financials.read', 37),
  ('client.read', 'client', 'read', 'authz.perm.client.read', 38),
  ('client.create', 'client', 'create', 'authz.perm.client.create', 39),
  ('client.update', 'client', 'update', 'authz.perm.client.update', 40),
  ('engagement.read', 'engagement', 'read', 'authz.perm.engagement.read', 41),
  ('engagement.create', 'engagement', 'create', 'authz.perm.engagement.create', 42),
  ('engagement.update', 'engagement', 'update', 'authz.perm.engagement.update', 43),
  ('engagement.delete', 'engagement', 'delete', 'authz.perm.engagement.delete', 44),
  ('worksheet.read', 'worksheet', 'read', 'authz.perm.worksheet.read', 45),
  ('worksheet.create', 'worksheet', 'create', 'authz.perm.worksheet.create', 46),
  ('worksheet.update', 'worksheet', 'update', 'authz.perm.worksheet.update', 47),
  ('worksheet.approve', 'worksheet', 'approve', 'authz.perm.worksheet.approve', 48),
  ('work_order.read', 'work_order', 'read', 'authz.perm.work_order.read', 49),
  ('work_order.create', 'work_order', 'create', 'authz.perm.work_order.create', 50),
  ('work_order.update', 'work_order', 'update', 'authz.perm.work_order.update', 51),
  ('work_order.submit', 'work_order', 'submit', 'authz.perm.work_order.submit', 52),
  ('work_order.payment_plan.approve', 'work_order', 'payment_plan.approve', 'authz.perm.work_order.payment_plan.approve', 53),
  ('work_order.risk.approve', 'work_order', 'risk.approve', 'authz.perm.work_order.risk.approve', 54),
  ('time_entry.read', 'time_entry', 'read', 'authz.perm.time_entry.read', 55),
  ('time_entry.create', 'time_entry', 'create', 'authz.perm.time_entry.create', 56),
  ('time_entry.update', 'time_entry', 'update', 'authz.perm.time_entry.update', 57),
  ('time_entry.delete', 'time_entry', 'delete', 'authz.perm.time_entry.delete', 58),
  ('timer.use', 'timer', 'use', 'authz.perm.timer.use', 59),
  ('timesheet.export', 'timesheet', 'export', 'authz.perm.timesheet.export', 60),
  ('timesheet.read', 'timesheet', 'read', 'authz.perm.timesheet.read', 61),
  ('timesheet.create', 'timesheet', 'create', 'authz.perm.timesheet.create', 62),
  ('timesheet.update_current', 'timesheet', 'update_current', 'authz.perm.timesheet.update_current', 63),
  ('timesheet.pending_hours.read', 'timesheet', 'pending_hours.read', 'authz.perm.timesheet.pending_hours.read', 64),
  ('timesheet.withdraw', 'timesheet', 'withdraw', 'authz.perm.timesheet.withdraw', 65),
  ('timesheet_approval.read', 'timesheet_approval', 'read', 'authz.perm.timesheet_approval.read', 66),
  ('timesheet_approval.approve', 'timesheet_approval', 'approve', 'authz.perm.timesheet_approval.approve', 67),
  ('timesheet_approval.reject', 'timesheet_approval', 'reject', 'authz.perm.timesheet_approval.reject', 68),
  ('timesheet_admin_training_approval.manage', 'timesheet_approval', 'timesheet_admin_training_approval.manage', 'authz.perm.timesheet_admin_training_approval.manage', 69),
  ('fund_request.read', 'fund_request', 'read', 'authz.perm.fund_request.read', 70),
  ('fund_request.create', 'fund_request', 'create', 'authz.perm.fund_request.create', 71),
  ('fund_request.update', 'fund_request', 'update', 'authz.perm.fund_request.update', 72),
  ('fund_request.delete', 'fund_request', 'delete', 'authz.perm.fund_request.delete', 73),
  ('fund_approval.read', 'fund_approval', 'read', 'authz.perm.fund_approval.read', 74),
  ('fund_approval.update', 'fund_approval', 'update', 'authz.perm.fund_approval.update', 75),
  ('fund_disbursement.read', 'fund_disbursement', 'read', 'authz.perm.fund_disbursement.read', 76),
  ('fund_disbursement.update', 'fund_disbursement', 'update', 'authz.perm.fund_disbursement.update', 77),
  ('fund_expense.read', 'fund_expense', 'read', 'authz.perm.fund_expense.read', 78),
  ('fund_expense.create', 'fund_expense', 'create', 'authz.perm.fund_expense.create', 79),
  ('fund_expense.update', 'fund_expense', 'update', 'authz.perm.fund_expense.update', 80),
  ('fund_expense.delete', 'fund_expense', 'delete', 'authz.perm.fund_expense.delete', 81),
  ('expense_settlement.read', 'expense_settlement', 'read', 'authz.perm.expense_settlement.read', 82),
  ('expense_settlement.update', 'expense_settlement', 'update', 'authz.perm.expense_settlement.update', 83)
on conflict (permission_key) do nothing;

-- C) Concesiones rol×permiso con scope_key (737)
insert into public.authorization_role_permissions (role_key, permission_key, scope_key) values
  ('admin', 'staff.read', 'none'),
  ('it_security_manager', 'staff.read', 'none'),
  ('senior_partner', 'staff.read', 'none'),
  ('partner', 'staff.read', 'none'),
  ('sqr', 'staff.read', 'none'),
  ('director', 'staff.read', 'none'),
  ('manager', 'staff.read', 'none'),
  ('ita_manager', 'staff.read', 'none'),
  ('tax_manager', 'staff.read', 'none'),
  ('accounting_manager', 'staff.read', 'none'),
  ('risk_partner', 'staff.read', 'none'),
  ('hr_manager', 'staff.read', 'none'),
  ('hr_analyst', 'staff.read', 'none'),
  ('admin', 'staff.update', 'none'),
  ('admin', 'staff.create', 'none'),
  ('admin', 'staff.delete', 'none'),
  ('admin', 'account.password.change', 'own'),
  ('it_security_manager', 'account.password.change', 'own'),
  ('senior_partner', 'account.password.change', 'own'),
  ('partner', 'account.password.change', 'own'),
  ('sqr', 'account.password.change', 'own'),
  ('director', 'account.password.change', 'own'),
  ('manager', 'account.password.change', 'own'),
  ('senior', 'account.password.change', 'own'),
  ('semisenior', 'account.password.change', 'own'),
  ('assistant', 'account.password.change', 'own'),
  ('ita_manager', 'account.password.change', 'own'),
  ('ita_senior', 'account.password.change', 'own'),
  ('ita_assistant', 'account.password.change', 'own'),
  ('tax_manager', 'account.password.change', 'own'),
  ('tax_senior', 'account.password.change', 'own'),
  ('tax_assistant', 'account.password.change', 'own'),
  ('accounting_manager', 'account.password.change', 'own'),
  ('accounting_analyst', 'account.password.change', 'own'),
  ('collections_analyst', 'account.password.change', 'own'),
  ('risk_partner', 'account.password.change', 'own'),
  ('risk_supervisor', 'account.password.change', 'own'),
  ('hr_manager', 'account.password.change', 'own'),
  ('hr_analyst', 'account.password.change', 'own'),
  ('admin', 'industry.read', 'none'),
  ('senior_partner', 'industry.read', 'none'),
  ('partner', 'industry.read', 'none'),
  ('sqr', 'industry.read', 'none'),
  ('director', 'industry.read', 'none'),
  ('manager', 'industry.read', 'none'),
  ('ita_manager', 'industry.read', 'none'),
  ('tax_manager', 'industry.read', 'none'),
  ('accounting_manager', 'industry.read', 'none'),
  ('risk_partner', 'industry.read', 'none'),
  ('admin', 'industry.create', 'none'),
  ('admin', 'industry.update', 'none'),
  ('admin', 'industry.delete', 'none'),
  ('admin', 'competency.read', 'none'),
  ('senior_partner', 'competency.read', 'none'),
  ('partner', 'competency.read', 'none'),
  ('sqr', 'competency.read', 'none'),
  ('director', 'competency.read', 'none'),
  ('manager', 'competency.read', 'none'),
  ('ita_manager', 'competency.read', 'none'),
  ('tax_manager', 'competency.read', 'none'),
  ('accounting_manager', 'competency.read', 'none'),
  ('risk_partner', 'competency.read', 'none'),
  ('hr_manager', 'competency.read', 'none'),
  ('hr_analyst', 'competency.read', 'none'),
  ('admin', 'competency.create', 'none'),
  ('hr_manager', 'competency.create', 'none'),
  ('hr_analyst', 'competency.create', 'none'),
  ('admin', 'competency.update', 'none'),
  ('hr_manager', 'competency.update', 'none'),
  ('hr_analyst', 'competency.update', 'none'),
  ('admin', 'competency.delete', 'none'),
  ('hr_manager', 'competency.delete', 'none'),
  ('hr_analyst', 'competency.delete', 'none'),
  ('admin', 'category_rate.read', 'none'),
  ('senior_partner', 'category_rate.read', 'none'),
  ('partner', 'category_rate.read', 'none'),
  ('sqr', 'category_rate.read', 'none'),
  ('director', 'category_rate.read', 'none'),
  ('manager', 'category_rate.read', 'none'),
  ('ita_manager', 'category_rate.read', 'none'),
  ('tax_manager', 'category_rate.read', 'none'),
  ('accounting_manager', 'category_rate.read', 'none'),
  ('risk_partner', 'category_rate.read', 'none'),
  ('admin', 'category_rate.create', 'none'),
  ('admin', 'category_rate.update', 'none'),
  ('admin', 'category_rate.delete', 'none'),
  ('admin', 'activity_code.read', 'none'),
  ('it_security_manager', 'activity_code.read', 'none'),
  ('senior_partner', 'activity_code.read', 'none'),
  ('partner', 'activity_code.read', 'none'),
  ('sqr', 'activity_code.read', 'none'),
  ('director', 'activity_code.read', 'none'),
  ('manager', 'activity_code.read', 'none'),
  ('senior', 'activity_code.read', 'none'),
  ('semisenior', 'activity_code.read', 'none'),
  ('assistant', 'activity_code.read', 'none'),
  ('ita_manager', 'activity_code.read', 'none'),
  ('ita_senior', 'activity_code.read', 'none'),
  ('ita_assistant', 'activity_code.read', 'none'),
  ('tax_manager', 'activity_code.read', 'none'),
  ('tax_senior', 'activity_code.read', 'none'),
  ('tax_assistant', 'activity_code.read', 'none'),
  ('admin', 'activity_code.create', 'none'),
  ('admin', 'activity_code.update', 'none'),
  ('admin', 'activity_code.delete', 'none'),
  ('admin', 'expense_type.read', 'none'),
  ('it_security_manager', 'expense_type.read', 'none'),
  ('senior_partner', 'expense_type.read', 'none'),
  ('partner', 'expense_type.read', 'none'),
  ('sqr', 'expense_type.read', 'none'),
  ('director', 'expense_type.read', 'none'),
  ('manager', 'expense_type.read', 'none'),
  ('senior', 'expense_type.read', 'none'),
  ('semisenior', 'expense_type.read', 'none'),
  ('assistant', 'expense_type.read', 'none'),
  ('ita_manager', 'expense_type.read', 'none'),
  ('ita_senior', 'expense_type.read', 'none'),
  ('ita_assistant', 'expense_type.read', 'none'),
  ('tax_manager', 'expense_type.read', 'none'),
  ('tax_senior', 'expense_type.read', 'none'),
  ('tax_assistant', 'expense_type.read', 'none'),
  ('accounting_manager', 'expense_type.read', 'none'),
  ('accounting_analyst', 'expense_type.read', 'none'),
  ('collections_analyst', 'expense_type.read', 'none'),
  ('risk_partner', 'expense_type.read', 'none'),
  ('risk_supervisor', 'expense_type.read', 'none'),
  ('hr_manager', 'expense_type.read', 'none'),
  ('hr_analyst', 'expense_type.read', 'none'),
  ('admin', 'expense_type.create', 'none'),
  ('accounting_manager', 'expense_type.create', 'none'),
  ('accounting_analyst', 'expense_type.create', 'none'),
  ('collections_analyst', 'expense_type.create', 'none'),
  ('admin', 'expense_type.update', 'none'),
  ('accounting_manager', 'expense_type.update', 'none'),
  ('accounting_analyst', 'expense_type.update', 'none'),
  ('collections_analyst', 'expense_type.update', 'none'),
  ('admin', 'expense_type.delete', 'none'),
  ('accounting_manager', 'expense_type.delete', 'none'),
  ('accounting_analyst', 'expense_type.delete', 'none'),
  ('collections_analyst', 'expense_type.delete', 'none'),
  ('admin', 'holiday.read', 'none'),
  ('it_security_manager', 'holiday.read', 'none'),
  ('senior_partner', 'holiday.read', 'none'),
  ('partner', 'holiday.read', 'none'),
  ('sqr', 'holiday.read', 'none'),
  ('director', 'holiday.read', 'none'),
  ('manager', 'holiday.read', 'none'),
  ('senior', 'holiday.read', 'none'),
  ('semisenior', 'holiday.read', 'none'),
  ('assistant', 'holiday.read', 'none'),
  ('ita_manager', 'holiday.read', 'none'),
  ('ita_senior', 'holiday.read', 'none'),
  ('ita_assistant', 'holiday.read', 'none'),
  ('tax_manager', 'holiday.read', 'none'),
  ('tax_senior', 'holiday.read', 'none'),
  ('tax_assistant', 'holiday.read', 'none'),
  ('accounting_manager', 'holiday.read', 'none'),
  ('accounting_analyst', 'holiday.read', 'none'),
  ('collections_analyst', 'holiday.read', 'none'),
  ('risk_partner', 'holiday.read', 'none'),
  ('risk_supervisor', 'holiday.read', 'none'),
  ('hr_manager', 'holiday.read', 'none'),
  ('hr_analyst', 'holiday.read', 'none'),
  ('admin', 'holiday.create', 'none'),
  ('hr_manager', 'holiday.create', 'none'),
  ('hr_analyst', 'holiday.create', 'none'),
  ('admin', 'holiday.update', 'none'),
  ('hr_manager', 'holiday.update', 'none'),
  ('hr_analyst', 'holiday.update', 'none'),
  ('admin', 'holiday.delete', 'none'),
  ('hr_manager', 'holiday.delete', 'none'),
  ('hr_analyst', 'holiday.delete', 'none'),
  ('admin', 'user_role.read', 'none'),
  ('it_security_manager', 'user_role.read', 'none'),
  ('admin', 'user_role.update', 'none'),
  ('admin', 'staff_profile.create_from_account', 'none'),
  ('admin', 'auth_account.delete', 'none'),
  ('admin', 'global_settings.update', 'none'),
  ('admin', 'dashboard.portfolio.read', 'firm'),
  ('senior_partner', 'dashboard.portfolio.read', 'firm'),
  ('partner', 'dashboard.portfolio.read', 'assigned_engagements'),
  ('director', 'dashboard.portfolio.read', 'assigned_engagements'),
  ('manager', 'dashboard.portfolio.read', 'assigned_engagements'),
  ('ita_manager', 'dashboard.portfolio.read', 'assigned_engagements'),
  ('tax_manager', 'dashboard.portfolio.read', 'assigned_engagements'),
  ('risk_partner', 'dashboard.portfolio.read', 'department'),
  ('admin', 'dashboard.engagement.read', 'firm'),
  ('senior_partner', 'dashboard.engagement.read', 'firm'),
  ('partner', 'dashboard.engagement.read', 'assigned_engagements'),
  ('sqr', 'dashboard.engagement.read', 'assigned_engagements'),
  ('director', 'dashboard.engagement.read', 'assigned_engagements'),
  ('manager', 'dashboard.engagement.read', 'assigned_engagements'),
  ('senior', 'dashboard.engagement.read', 'assigned_engagements'),
  ('ita_manager', 'dashboard.engagement.read', 'assigned_engagements'),
  ('ita_senior', 'dashboard.engagement.read', 'assigned_engagements'),
  ('tax_manager', 'dashboard.engagement.read', 'assigned_engagements'),
  ('tax_senior', 'dashboard.engagement.read', 'assigned_engagements'),
  ('risk_partner', 'dashboard.engagement.read', 'department'),
  ('admin', 'dashboard.personal.read', 'own'),
  ('it_security_manager', 'dashboard.personal.read', 'own'),
  ('senior_partner', 'dashboard.personal.read', 'own'),
  ('partner', 'dashboard.personal.read', 'own'),
  ('sqr', 'dashboard.personal.read', 'own'),
  ('director', 'dashboard.personal.read', 'own'),
  ('manager', 'dashboard.personal.read', 'own'),
  ('senior', 'dashboard.personal.read', 'own'),
  ('semisenior', 'dashboard.personal.read', 'own'),
  ('assistant', 'dashboard.personal.read', 'own'),
  ('ita_manager', 'dashboard.personal.read', 'own'),
  ('ita_senior', 'dashboard.personal.read', 'own'),
  ('ita_assistant', 'dashboard.personal.read', 'own'),
  ('tax_manager', 'dashboard.personal.read', 'own'),
  ('tax_senior', 'dashboard.personal.read', 'own'),
  ('tax_assistant', 'dashboard.personal.read', 'own'),
  ('accounting_manager', 'dashboard.personal.read', 'own'),
  ('accounting_analyst', 'dashboard.personal.read', 'own'),
  ('collections_analyst', 'dashboard.personal.read', 'own'),
  ('risk_partner', 'dashboard.personal.read', 'own'),
  ('risk_supervisor', 'dashboard.personal.read', 'own'),
  ('hr_manager', 'dashboard.personal.read', 'own'),
  ('hr_analyst', 'dashboard.personal.read', 'own'),
  ('admin', 'dashboard.practice_financials.read', 'firm'),
  ('senior_partner', 'dashboard.practice_financials.read', 'firm'),
  ('partner', 'dashboard.practice_financials.read', 'firm'),
  ('risk_partner', 'dashboard.practice_financials.read', 'firm'),
  ('admin', 'client.read', 'firm'),
  ('it_security_manager', 'client.read', 'firm'),
  ('senior_partner', 'client.read', 'firm'),
  ('partner', 'client.read', 'assigned_clients'),
  ('sqr', 'client.read', 'assigned_clients'),
  ('director', 'client.read', 'assigned_clients'),
  ('manager', 'client.read', 'assigned_clients'),
  ('ita_manager', 'client.read', 'assigned_clients'),
  ('tax_manager', 'client.read', 'assigned_clients'),
  ('risk_partner', 'client.read', 'department'),
  ('admin', 'client.create', 'firm'),
  ('senior_partner', 'client.create', 'firm'),
  ('partner', 'client.create', 'assigned_clients'),
  ('sqr', 'client.create', 'assigned_clients'),
  ('director', 'client.create', 'assigned_clients'),
  ('manager', 'client.create', 'assigned_clients'),
  ('ita_manager', 'client.create', 'assigned_clients'),
  ('tax_manager', 'client.create', 'assigned_clients'),
  ('admin', 'client.update', 'firm'),
  ('admin', 'engagement.read', 'firm'),
  ('it_security_manager', 'engagement.read', 'firm'),
  ('senior_partner', 'engagement.read', 'firm'),
  ('partner', 'engagement.read', 'assigned_engagements'),
  ('sqr', 'engagement.read', 'assigned_engagements'),
  ('director', 'engagement.read', 'assigned_engagements'),
  ('manager', 'engagement.read', 'assigned_engagements'),
  ('ita_manager', 'engagement.read', 'assigned_engagements'),
  ('tax_manager', 'engagement.read', 'assigned_engagements'),
  ('risk_partner', 'engagement.read', 'department'),
  ('admin', 'engagement.create', 'firm'),
  ('manager', 'engagement.create', 'assigned_engagements'),
  ('ita_manager', 'engagement.create', 'assigned_engagements'),
  ('tax_manager', 'engagement.create', 'assigned_engagements'),
  ('admin', 'engagement.update', 'firm'),
  ('manager', 'engagement.update', 'assigned_engagements'),
  ('ita_manager', 'engagement.update', 'assigned_engagements'),
  ('tax_manager', 'engagement.update', 'assigned_engagements'),
  ('admin', 'engagement.delete', 'firm'),
  ('admin', 'worksheet.read', 'firm'),
  ('senior_partner', 'worksheet.read', 'firm'),
  ('partner', 'worksheet.read', 'assigned_engagements'),
  ('sqr', 'worksheet.read', 'assigned_engagements'),
  ('director', 'worksheet.read', 'assigned_engagements'),
  ('manager', 'worksheet.read', 'assigned_engagements'),
  ('ita_manager', 'worksheet.read', 'assigned_engagements'),
  ('tax_manager', 'worksheet.read', 'assigned_engagements'),
  ('risk_partner', 'worksheet.read', 'department'),
  ('admin', 'worksheet.create', 'firm'),
  ('manager', 'worksheet.create', 'assigned_engagements'),
  ('ita_manager', 'worksheet.create', 'assigned_engagements'),
  ('tax_manager', 'worksheet.create', 'assigned_engagements'),
  ('risk_partner', 'worksheet.create', 'department'),
  ('admin', 'worksheet.update', 'firm'),
  ('manager', 'worksheet.update', 'assigned_engagements'),
  ('ita_manager', 'worksheet.update', 'assigned_engagements'),
  ('tax_manager', 'worksheet.update', 'assigned_engagements'),
  ('risk_partner', 'worksheet.update', 'department'),
  ('admin', 'worksheet.approve', 'firm'),
  ('senior_partner', 'worksheet.approve', 'firm'),
  ('partner', 'worksheet.approve', 'assigned_engagements'),
  ('director', 'worksheet.approve', 'assigned_engagements'),
  ('risk_partner', 'worksheet.approve', 'department'),
  ('admin', 'work_order.read', 'firm'),
  ('senior_partner', 'work_order.read', 'firm'),
  ('partner', 'work_order.read', 'assigned_engagements'),
  ('sqr', 'work_order.read', 'assigned_engagements'),
  ('director', 'work_order.read', 'assigned_engagements'),
  ('manager', 'work_order.read', 'assigned_engagements'),
  ('ita_manager', 'work_order.read', 'assigned_engagements'),
  ('tax_manager', 'work_order.read', 'assigned_engagements'),
  ('admin', 'work_order.create', 'firm'),
  ('senior_partner', 'work_order.create', 'firm'),
  ('partner', 'work_order.create', 'assigned_engagements'),
  ('manager', 'work_order.create', 'assigned_engagements'),
  ('ita_manager', 'work_order.create', 'assigned_engagements'),
  ('tax_manager', 'work_order.create', 'assigned_engagements'),
  ('admin', 'work_order.update', 'firm'),
  ('manager', 'work_order.update', 'assigned_engagements'),
  ('ita_manager', 'work_order.update', 'assigned_engagements'),
  ('tax_manager', 'work_order.update', 'assigned_engagements'),
  ('admin', 'work_order.submit', 'firm'),
  ('senior_partner', 'work_order.submit', 'firm'),
  ('partner', 'work_order.submit', 'assigned_engagements'),
  ('director', 'work_order.submit', 'assigned_engagements'),
  ('admin', 'work_order.payment_plan.approve', 'firm'),
  ('senior_partner', 'work_order.payment_plan.approve', 'firm'),
  ('partner', 'work_order.payment_plan.approve', 'assigned_engagements'),
  ('sqr', 'work_order.payment_plan.approve', 'assigned_engagements'),
  ('director', 'work_order.payment_plan.approve', 'assigned_engagements'),
  ('manager', 'work_order.payment_plan.approve', 'assigned_engagements'),
  ('ita_manager', 'work_order.payment_plan.approve', 'assigned_engagements'),
  ('tax_manager', 'work_order.payment_plan.approve', 'assigned_engagements'),
  ('accounting_manager', 'work_order.payment_plan.approve', 'department'),
  ('collections_analyst', 'work_order.payment_plan.approve', 'department'),
  ('admin', 'work_order.risk.approve', 'assigned_engagements'),
  ('manager', 'work_order.risk.approve', 'assigned_engagements'),
  ('ita_manager', 'work_order.risk.approve', 'assigned_engagements'),
  ('tax_manager', 'work_order.risk.approve', 'assigned_engagements'),
  ('risk_partner', 'work_order.risk.approve', 'department'),
  ('risk_supervisor', 'work_order.risk.approve', 'department'),
  ('admin', 'time_entry.read', 'own'),
  ('it_security_manager', 'time_entry.read', 'own'),
  ('senior_partner', 'time_entry.read', 'own'),
  ('partner', 'time_entry.read', 'own'),
  ('sqr', 'time_entry.read', 'own'),
  ('director', 'time_entry.read', 'own'),
  ('manager', 'time_entry.read', 'own'),
  ('senior', 'time_entry.read', 'own'),
  ('semisenior', 'time_entry.read', 'own'),
  ('assistant', 'time_entry.read', 'own'),
  ('ita_manager', 'time_entry.read', 'own'),
  ('ita_senior', 'time_entry.read', 'own'),
  ('ita_assistant', 'time_entry.read', 'own'),
  ('tax_manager', 'time_entry.read', 'own'),
  ('tax_senior', 'time_entry.read', 'own'),
  ('tax_assistant', 'time_entry.read', 'own'),
  ('risk_partner', 'time_entry.read', 'own'),
  ('admin', 'time_entry.create', 'own'),
  ('it_security_manager', 'time_entry.create', 'own'),
  ('senior_partner', 'time_entry.create', 'own'),
  ('partner', 'time_entry.create', 'own'),
  ('sqr', 'time_entry.create', 'own'),
  ('director', 'time_entry.create', 'own'),
  ('manager', 'time_entry.create', 'own'),
  ('senior', 'time_entry.create', 'own'),
  ('semisenior', 'time_entry.create', 'own'),
  ('assistant', 'time_entry.create', 'own'),
  ('ita_manager', 'time_entry.create', 'own'),
  ('ita_senior', 'time_entry.create', 'own'),
  ('ita_assistant', 'time_entry.create', 'own'),
  ('tax_manager', 'time_entry.create', 'own'),
  ('tax_senior', 'time_entry.create', 'own'),
  ('tax_assistant', 'time_entry.create', 'own'),
  ('risk_partner', 'time_entry.create', 'own'),
  ('admin', 'time_entry.update', 'own'),
  ('it_security_manager', 'time_entry.update', 'own'),
  ('senior_partner', 'time_entry.update', 'own'),
  ('partner', 'time_entry.update', 'own'),
  ('sqr', 'time_entry.update', 'own'),
  ('director', 'time_entry.update', 'own'),
  ('manager', 'time_entry.update', 'own'),
  ('senior', 'time_entry.update', 'own'),
  ('semisenior', 'time_entry.update', 'own'),
  ('assistant', 'time_entry.update', 'own'),
  ('ita_manager', 'time_entry.update', 'own'),
  ('ita_senior', 'time_entry.update', 'own'),
  ('ita_assistant', 'time_entry.update', 'own'),
  ('tax_manager', 'time_entry.update', 'own'),
  ('tax_senior', 'time_entry.update', 'own'),
  ('tax_assistant', 'time_entry.update', 'own'),
  ('risk_partner', 'time_entry.update', 'own'),
  ('admin', 'time_entry.delete', 'own'),
  ('it_security_manager', 'time_entry.delete', 'own'),
  ('senior_partner', 'time_entry.delete', 'own'),
  ('partner', 'time_entry.delete', 'own'),
  ('sqr', 'time_entry.delete', 'own'),
  ('director', 'time_entry.delete', 'own'),
  ('manager', 'time_entry.delete', 'own'),
  ('senior', 'time_entry.delete', 'own'),
  ('semisenior', 'time_entry.delete', 'own'),
  ('assistant', 'time_entry.delete', 'own'),
  ('ita_manager', 'time_entry.delete', 'own'),
  ('ita_senior', 'time_entry.delete', 'own'),
  ('ita_assistant', 'time_entry.delete', 'own'),
  ('tax_manager', 'time_entry.delete', 'own'),
  ('tax_senior', 'time_entry.delete', 'own'),
  ('tax_assistant', 'time_entry.delete', 'own'),
  ('risk_partner', 'time_entry.delete', 'own'),
  ('admin', 'timer.use', 'own'),
  ('it_security_manager', 'timer.use', 'own'),
  ('senior_partner', 'timer.use', 'own'),
  ('partner', 'timer.use', 'own'),
  ('sqr', 'timer.use', 'own'),
  ('director', 'timer.use', 'own'),
  ('manager', 'timer.use', 'own'),
  ('senior', 'timer.use', 'own'),
  ('semisenior', 'timer.use', 'own'),
  ('assistant', 'timer.use', 'own'),
  ('ita_manager', 'timer.use', 'own'),
  ('ita_senior', 'timer.use', 'own'),
  ('ita_assistant', 'timer.use', 'own'),
  ('tax_manager', 'timer.use', 'own'),
  ('tax_senior', 'timer.use', 'own'),
  ('tax_assistant', 'timer.use', 'own'),
  ('risk_partner', 'timer.use', 'own'),
  ('admin', 'timesheet.export', 'own'),
  ('it_security_manager', 'timesheet.export', 'own'),
  ('senior_partner', 'timesheet.export', 'own'),
  ('partner', 'timesheet.export', 'own'),
  ('sqr', 'timesheet.export', 'own'),
  ('director', 'timesheet.export', 'own'),
  ('manager', 'timesheet.export', 'own'),
  ('senior', 'timesheet.export', 'own'),
  ('semisenior', 'timesheet.export', 'own'),
  ('assistant', 'timesheet.export', 'own'),
  ('ita_manager', 'timesheet.export', 'own'),
  ('ita_senior', 'timesheet.export', 'own'),
  ('ita_assistant', 'timesheet.export', 'own'),
  ('tax_manager', 'timesheet.export', 'own'),
  ('tax_senior', 'timesheet.export', 'own'),
  ('tax_assistant', 'timesheet.export', 'own'),
  ('risk_partner', 'timesheet.export', 'own'),
  ('admin', 'timesheet.read', 'own'),
  ('it_security_manager', 'timesheet.read', 'own'),
  ('senior_partner', 'timesheet.read', 'own'),
  ('partner', 'timesheet.read', 'own'),
  ('sqr', 'timesheet.read', 'own'),
  ('director', 'timesheet.read', 'own'),
  ('manager', 'timesheet.read', 'own'),
  ('senior', 'timesheet.read', 'own'),
  ('semisenior', 'timesheet.read', 'own'),
  ('assistant', 'timesheet.read', 'own'),
  ('ita_manager', 'timesheet.read', 'own'),
  ('ita_senior', 'timesheet.read', 'own'),
  ('ita_assistant', 'timesheet.read', 'own'),
  ('tax_manager', 'timesheet.read', 'own'),
  ('tax_senior', 'timesheet.read', 'own'),
  ('tax_assistant', 'timesheet.read', 'own'),
  ('risk_partner', 'timesheet.read', 'own'),
  ('admin', 'timesheet.create', 'own'),
  ('it_security_manager', 'timesheet.create', 'own'),
  ('senior_partner', 'timesheet.create', 'own'),
  ('partner', 'timesheet.create', 'own'),
  ('sqr', 'timesheet.create', 'own'),
  ('director', 'timesheet.create', 'own'),
  ('manager', 'timesheet.create', 'own'),
  ('senior', 'timesheet.create', 'own'),
  ('semisenior', 'timesheet.create', 'own'),
  ('assistant', 'timesheet.create', 'own'),
  ('ita_manager', 'timesheet.create', 'own'),
  ('ita_senior', 'timesheet.create', 'own'),
  ('ita_assistant', 'timesheet.create', 'own'),
  ('tax_manager', 'timesheet.create', 'own'),
  ('tax_senior', 'timesheet.create', 'own'),
  ('tax_assistant', 'timesheet.create', 'own'),
  ('risk_partner', 'timesheet.create', 'own'),
  ('admin', 'timesheet.update_current', 'own'),
  ('it_security_manager', 'timesheet.update_current', 'own'),
  ('senior_partner', 'timesheet.update_current', 'own'),
  ('partner', 'timesheet.update_current', 'own'),
  ('sqr', 'timesheet.update_current', 'own'),
  ('director', 'timesheet.update_current', 'own'),
  ('manager', 'timesheet.update_current', 'own'),
  ('senior', 'timesheet.update_current', 'own'),
  ('semisenior', 'timesheet.update_current', 'own'),
  ('assistant', 'timesheet.update_current', 'own'),
  ('ita_manager', 'timesheet.update_current', 'own'),
  ('ita_senior', 'timesheet.update_current', 'own'),
  ('ita_assistant', 'timesheet.update_current', 'own'),
  ('tax_manager', 'timesheet.update_current', 'own'),
  ('tax_senior', 'timesheet.update_current', 'own'),
  ('tax_assistant', 'timesheet.update_current', 'own'),
  ('risk_partner', 'timesheet.update_current', 'own'),
  ('admin', 'timesheet.pending_hours.read', 'own'),
  ('it_security_manager', 'timesheet.pending_hours.read', 'own'),
  ('senior_partner', 'timesheet.pending_hours.read', 'own'),
  ('partner', 'timesheet.pending_hours.read', 'own'),
  ('sqr', 'timesheet.pending_hours.read', 'own'),
  ('director', 'timesheet.pending_hours.read', 'own'),
  ('manager', 'timesheet.pending_hours.read', 'own'),
  ('senior', 'timesheet.pending_hours.read', 'own'),
  ('semisenior', 'timesheet.pending_hours.read', 'own'),
  ('assistant', 'timesheet.pending_hours.read', 'own'),
  ('ita_manager', 'timesheet.pending_hours.read', 'own'),
  ('ita_senior', 'timesheet.pending_hours.read', 'own'),
  ('ita_assistant', 'timesheet.pending_hours.read', 'own'),
  ('tax_manager', 'timesheet.pending_hours.read', 'own'),
  ('tax_senior', 'timesheet.pending_hours.read', 'own'),
  ('tax_assistant', 'timesheet.pending_hours.read', 'own'),
  ('risk_partner', 'timesheet.pending_hours.read', 'own'),
  ('admin', 'timesheet.withdraw', 'own'),
  ('it_security_manager', 'timesheet.withdraw', 'own'),
  ('senior_partner', 'timesheet.withdraw', 'own'),
  ('partner', 'timesheet.withdraw', 'own'),
  ('sqr', 'timesheet.withdraw', 'own'),
  ('director', 'timesheet.withdraw', 'own'),
  ('manager', 'timesheet.withdraw', 'own'),
  ('senior', 'timesheet.withdraw', 'own'),
  ('semisenior', 'timesheet.withdraw', 'own'),
  ('assistant', 'timesheet.withdraw', 'own'),
  ('ita_manager', 'timesheet.withdraw', 'own'),
  ('ita_senior', 'timesheet.withdraw', 'own'),
  ('ita_assistant', 'timesheet.withdraw', 'own'),
  ('tax_manager', 'timesheet.withdraw', 'own'),
  ('tax_senior', 'timesheet.withdraw', 'own'),
  ('tax_assistant', 'timesheet.withdraw', 'own'),
  ('risk_partner', 'timesheet.withdraw', 'own'),
  ('admin', 'timesheet_approval.read', 'firm'),
  ('senior_partner', 'timesheet_approval.read', 'firm'),
  ('partner', 'timesheet_approval.read', 'assigned_engagements'),
  ('sqr', 'timesheet_approval.read', 'assigned_engagements'),
  ('director', 'timesheet_approval.read', 'assigned_engagements'),
  ('manager', 'timesheet_approval.read', 'assigned_engagements'),
  ('ita_manager', 'timesheet_approval.read', 'assigned_engagements'),
  ('tax_manager', 'timesheet_approval.read', 'assigned_engagements'),
  ('risk_partner', 'timesheet_approval.read', 'assigned_engagements'),
  ('admin', 'timesheet_approval.approve', 'firm'),
  ('manager', 'timesheet_approval.approve', 'assigned_engagements'),
  ('ita_manager', 'timesheet_approval.approve', 'assigned_engagements'),
  ('tax_manager', 'timesheet_approval.approve', 'assigned_engagements'),
  ('admin', 'timesheet_approval.reject', 'firm'),
  ('manager', 'timesheet_approval.reject', 'assigned_engagements'),
  ('ita_manager', 'timesheet_approval.reject', 'assigned_engagements'),
  ('tax_manager', 'timesheet_approval.reject', 'assigned_engagements'),
  ('admin', 'timesheet_admin_training_approval.manage', 'assigned_engagements'),
  ('manager', 'timesheet_admin_training_approval.manage', 'assigned_engagements'),
  ('ita_manager', 'timesheet_admin_training_approval.manage', 'assigned_engagements'),
  ('tax_manager', 'timesheet_admin_training_approval.manage', 'assigned_engagements'),
  ('hr_manager', 'timesheet_admin_training_approval.manage', 'department'),
  ('hr_analyst', 'timesheet_admin_training_approval.manage', 'department'),
  ('admin', 'fund_request.read', 'own'),
  ('it_security_manager', 'fund_request.read', 'own'),
  ('senior_partner', 'fund_request.read', 'own'),
  ('partner', 'fund_request.read', 'own'),
  ('sqr', 'fund_request.read', 'own'),
  ('director', 'fund_request.read', 'own'),
  ('manager', 'fund_request.read', 'own'),
  ('senior', 'fund_request.read', 'own'),
  ('semisenior', 'fund_request.read', 'own'),
  ('assistant', 'fund_request.read', 'own'),
  ('ita_manager', 'fund_request.read', 'own'),
  ('ita_senior', 'fund_request.read', 'own'),
  ('ita_assistant', 'fund_request.read', 'own'),
  ('tax_manager', 'fund_request.read', 'own'),
  ('tax_senior', 'fund_request.read', 'own'),
  ('tax_assistant', 'fund_request.read', 'own'),
  ('accounting_manager', 'fund_request.read', 'own'),
  ('accounting_analyst', 'fund_request.read', 'own'),
  ('collections_analyst', 'fund_request.read', 'own'),
  ('risk_partner', 'fund_request.read', 'own'),
  ('risk_supervisor', 'fund_request.read', 'own'),
  ('hr_manager', 'fund_request.read', 'own'),
  ('hr_analyst', 'fund_request.read', 'own'),
  ('admin', 'fund_request.create', 'own'),
  ('it_security_manager', 'fund_request.create', 'own'),
  ('senior_partner', 'fund_request.create', 'own'),
  ('partner', 'fund_request.create', 'own'),
  ('sqr', 'fund_request.create', 'own'),
  ('director', 'fund_request.create', 'own'),
  ('manager', 'fund_request.create', 'own'),
  ('senior', 'fund_request.create', 'own'),
  ('semisenior', 'fund_request.create', 'own'),
  ('assistant', 'fund_request.create', 'own'),
  ('ita_manager', 'fund_request.create', 'own'),
  ('ita_senior', 'fund_request.create', 'own'),
  ('ita_assistant', 'fund_request.create', 'own'),
  ('tax_manager', 'fund_request.create', 'own'),
  ('tax_senior', 'fund_request.create', 'own'),
  ('tax_assistant', 'fund_request.create', 'own'),
  ('accounting_manager', 'fund_request.create', 'own'),
  ('accounting_analyst', 'fund_request.create', 'own'),
  ('collections_analyst', 'fund_request.create', 'own'),
  ('risk_partner', 'fund_request.create', 'own'),
  ('risk_supervisor', 'fund_request.create', 'own'),
  ('hr_manager', 'fund_request.create', 'own'),
  ('hr_analyst', 'fund_request.create', 'own'),
  ('admin', 'fund_request.update', 'own'),
  ('it_security_manager', 'fund_request.update', 'own'),
  ('senior_partner', 'fund_request.update', 'own'),
  ('partner', 'fund_request.update', 'own'),
  ('sqr', 'fund_request.update', 'own'),
  ('director', 'fund_request.update', 'own'),
  ('manager', 'fund_request.update', 'own'),
  ('senior', 'fund_request.update', 'own'),
  ('semisenior', 'fund_request.update', 'own'),
  ('assistant', 'fund_request.update', 'own'),
  ('ita_manager', 'fund_request.update', 'own'),
  ('ita_senior', 'fund_request.update', 'own'),
  ('ita_assistant', 'fund_request.update', 'own'),
  ('tax_manager', 'fund_request.update', 'own'),
  ('tax_senior', 'fund_request.update', 'own'),
  ('tax_assistant', 'fund_request.update', 'own'),
  ('accounting_manager', 'fund_request.update', 'own'),
  ('accounting_analyst', 'fund_request.update', 'own'),
  ('collections_analyst', 'fund_request.update', 'own'),
  ('risk_partner', 'fund_request.update', 'own'),
  ('risk_supervisor', 'fund_request.update', 'own'),
  ('hr_manager', 'fund_request.update', 'own'),
  ('hr_analyst', 'fund_request.update', 'own'),
  ('admin', 'fund_request.delete', 'own'),
  ('it_security_manager', 'fund_request.delete', 'own'),
  ('senior_partner', 'fund_request.delete', 'own'),
  ('partner', 'fund_request.delete', 'own'),
  ('sqr', 'fund_request.delete', 'own'),
  ('director', 'fund_request.delete', 'own'),
  ('manager', 'fund_request.delete', 'own'),
  ('senior', 'fund_request.delete', 'own'),
  ('semisenior', 'fund_request.delete', 'own'),
  ('assistant', 'fund_request.delete', 'own'),
  ('ita_manager', 'fund_request.delete', 'own'),
  ('ita_senior', 'fund_request.delete', 'own'),
  ('ita_assistant', 'fund_request.delete', 'own'),
  ('tax_manager', 'fund_request.delete', 'own'),
  ('tax_senior', 'fund_request.delete', 'own'),
  ('tax_assistant', 'fund_request.delete', 'own'),
  ('accounting_manager', 'fund_request.delete', 'own'),
  ('accounting_analyst', 'fund_request.delete', 'own'),
  ('collections_analyst', 'fund_request.delete', 'own'),
  ('risk_partner', 'fund_request.delete', 'own'),
  ('risk_supervisor', 'fund_request.delete', 'own'),
  ('hr_manager', 'fund_request.delete', 'own'),
  ('hr_analyst', 'fund_request.delete', 'own'),
  ('admin', 'fund_approval.read', 'firm'),
  ('manager', 'fund_approval.read', 'assigned_engagements'),
  ('ita_manager', 'fund_approval.read', 'assigned_engagements'),
  ('tax_manager', 'fund_approval.read', 'assigned_engagements'),
  ('admin', 'fund_approval.update', 'firm'),
  ('manager', 'fund_approval.update', 'assigned_engagements'),
  ('ita_manager', 'fund_approval.update', 'assigned_engagements'),
  ('tax_manager', 'fund_approval.update', 'assigned_engagements'),
  ('admin', 'fund_disbursement.read', 'department'),
  ('accounting_manager', 'fund_disbursement.read', 'department'),
  ('admin', 'fund_disbursement.update', 'department'),
  ('accounting_manager', 'fund_disbursement.update', 'department'),
  ('admin', 'fund_expense.read', 'own'),
  ('it_security_manager', 'fund_expense.read', 'own'),
  ('senior_partner', 'fund_expense.read', 'own'),
  ('partner', 'fund_expense.read', 'own'),
  ('sqr', 'fund_expense.read', 'own'),
  ('director', 'fund_expense.read', 'own'),
  ('manager', 'fund_expense.read', 'own'),
  ('senior', 'fund_expense.read', 'own'),
  ('semisenior', 'fund_expense.read', 'own'),
  ('assistant', 'fund_expense.read', 'own'),
  ('ita_manager', 'fund_expense.read', 'own'),
  ('ita_senior', 'fund_expense.read', 'own'),
  ('ita_assistant', 'fund_expense.read', 'own'),
  ('tax_manager', 'fund_expense.read', 'own'),
  ('tax_senior', 'fund_expense.read', 'own'),
  ('tax_assistant', 'fund_expense.read', 'own'),
  ('accounting_manager', 'fund_expense.read', 'own'),
  ('accounting_analyst', 'fund_expense.read', 'own'),
  ('collections_analyst', 'fund_expense.read', 'own'),
  ('risk_partner', 'fund_expense.read', 'own'),
  ('risk_supervisor', 'fund_expense.read', 'own'),
  ('hr_manager', 'fund_expense.read', 'own'),
  ('hr_analyst', 'fund_expense.read', 'own'),
  ('admin', 'fund_expense.create', 'own'),
  ('it_security_manager', 'fund_expense.create', 'own'),
  ('senior_partner', 'fund_expense.create', 'own'),
  ('partner', 'fund_expense.create', 'own'),
  ('sqr', 'fund_expense.create', 'own'),
  ('director', 'fund_expense.create', 'own'),
  ('manager', 'fund_expense.create', 'own'),
  ('senior', 'fund_expense.create', 'own'),
  ('semisenior', 'fund_expense.create', 'own'),
  ('assistant', 'fund_expense.create', 'own'),
  ('ita_manager', 'fund_expense.create', 'own'),
  ('ita_senior', 'fund_expense.create', 'own'),
  ('ita_assistant', 'fund_expense.create', 'own'),
  ('tax_manager', 'fund_expense.create', 'own'),
  ('tax_senior', 'fund_expense.create', 'own'),
  ('tax_assistant', 'fund_expense.create', 'own'),
  ('accounting_manager', 'fund_expense.create', 'own'),
  ('accounting_analyst', 'fund_expense.create', 'own'),
  ('collections_analyst', 'fund_expense.create', 'own'),
  ('risk_partner', 'fund_expense.create', 'own'),
  ('risk_supervisor', 'fund_expense.create', 'own'),
  ('hr_manager', 'fund_expense.create', 'own'),
  ('hr_analyst', 'fund_expense.create', 'own'),
  ('admin', 'fund_expense.update', 'own'),
  ('it_security_manager', 'fund_expense.update', 'own'),
  ('senior_partner', 'fund_expense.update', 'own'),
  ('partner', 'fund_expense.update', 'own'),
  ('sqr', 'fund_expense.update', 'own'),
  ('director', 'fund_expense.update', 'own'),
  ('manager', 'fund_expense.update', 'own'),
  ('senior', 'fund_expense.update', 'own'),
  ('semisenior', 'fund_expense.update', 'own'),
  ('assistant', 'fund_expense.update', 'own'),
  ('ita_manager', 'fund_expense.update', 'own'),
  ('ita_senior', 'fund_expense.update', 'own'),
  ('ita_assistant', 'fund_expense.update', 'own'),
  ('tax_manager', 'fund_expense.update', 'own'),
  ('tax_senior', 'fund_expense.update', 'own'),
  ('tax_assistant', 'fund_expense.update', 'own'),
  ('accounting_manager', 'fund_expense.update', 'own'),
  ('accounting_analyst', 'fund_expense.update', 'own'),
  ('collections_analyst', 'fund_expense.update', 'own'),
  ('risk_partner', 'fund_expense.update', 'own'),
  ('risk_supervisor', 'fund_expense.update', 'own'),
  ('hr_manager', 'fund_expense.update', 'own'),
  ('hr_analyst', 'fund_expense.update', 'own'),
  ('admin', 'fund_expense.delete', 'own'),
  ('it_security_manager', 'fund_expense.delete', 'own'),
  ('senior_partner', 'fund_expense.delete', 'own'),
  ('partner', 'fund_expense.delete', 'own'),
  ('sqr', 'fund_expense.delete', 'own'),
  ('director', 'fund_expense.delete', 'own'),
  ('manager', 'fund_expense.delete', 'own'),
  ('senior', 'fund_expense.delete', 'own'),
  ('semisenior', 'fund_expense.delete', 'own'),
  ('assistant', 'fund_expense.delete', 'own'),
  ('ita_manager', 'fund_expense.delete', 'own'),
  ('ita_senior', 'fund_expense.delete', 'own'),
  ('ita_assistant', 'fund_expense.delete', 'own'),
  ('tax_manager', 'fund_expense.delete', 'own'),
  ('tax_senior', 'fund_expense.delete', 'own'),
  ('tax_assistant', 'fund_expense.delete', 'own'),
  ('accounting_manager', 'fund_expense.delete', 'own'),
  ('accounting_analyst', 'fund_expense.delete', 'own'),
  ('collections_analyst', 'fund_expense.delete', 'own'),
  ('risk_partner', 'fund_expense.delete', 'own'),
  ('risk_supervisor', 'fund_expense.delete', 'own'),
  ('hr_manager', 'fund_expense.delete', 'own'),
  ('hr_analyst', 'fund_expense.delete', 'own'),
  ('admin', 'expense_settlement.read', 'department'),
  ('accounting_manager', 'expense_settlement.read', 'department'),
  ('accounting_analyst', 'expense_settlement.read', 'department'),
  ('admin', 'expense_settlement.update', 'department'),
  ('accounting_manager', 'expense_settlement.update', 'department'),
  ('accounting_analyst', 'expense_settlement.update', 'department')
on conflict (role_key, permission_key) do update set scope_key = excluded.scope_key;

-- D) role_key en user_roles: la columna ya existe en el esquema consolidado (cero_02/cero_03,
-- no via ALTER histórico) y handle_new_user() ya escribe role_key='admin' para el bootstrap —
-- este bloque queda idéntico al original por fidelidad a la decisión del operador; es un
-- no-op seguro (ADD COLUMN IF NOT EXISTS sobre columna existente; UPDATE ... WHERE role_key IS
-- NULL no toca la fila del bootstrap, que ya nace con role_key asignado por el trigger).
alter table public.user_roles add column if not exists role_key text
  references public.authorization_roles(role_key);

update public.user_roles set role_key = case role::text
  when 'admin'      then 'admin'
  when 'partner'    then 'partner'      -- Socio por defecto; Senior Partner se reasigna a mano
  when 'director'   then 'director'
  when 'manager'    then 'manager'
  when 'senior'     then 'senior'
  when 'semisenior' then 'semisenior'
  when 'sqr'        then 'sqr'
  when 'staff'      then 'assistant'
  else null
end
where role_key is null;

create index if not exists idx_user_roles_role_key on public.user_roles(role_key);
