-- Expand app_role enum with new values
ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'partner';
ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'director';
ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'manager';
ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'senior';
ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'semisenior';

-- Disable RLS on all 20 tables for beta testing
ALTER TABLE activity_codes DISABLE ROW LEVEL SECURITY;
ALTER TABLE activity_worksheet_cells DISABLE ROW LEVEL SECURITY;
ALTER TABLE activity_worksheets DISABLE ROW LEVEL SECURITY;
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE clients DISABLE ROW LEVEL SECURITY;
ALTER TABLE engagements DISABLE ROW LEVEL SECURITY;
ALTER TABLE expense_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE expense_types DISABLE ROW LEVEL SECURITY;
ALTER TABLE global_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE industries DISABLE ROW LEVEL SECURITY;
ALTER TABLE staff DISABLE ROW LEVEL SECURITY;
ALTER TABLE staff_capacity DISABLE ROW LEVEL SECURITY;
ALTER TABLE time_entries DISABLE ROW LEVEL SECURITY;
ALTER TABLE timer_entries DISABLE ROW LEVEL SECURITY;
ALTER TABLE timesheet_line_approvals DISABLE ROW LEVEL SECURITY;
ALTER TABLE timesheet_periods DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_roles DISABLE ROW LEVEL SECURITY;
ALTER TABLE wo_budget_lines DISABLE ROW LEVEL SECURITY;
ALTER TABLE wo_expense_budget DISABLE ROW LEVEL SECURITY;
ALTER TABLE work_orders DISABLE ROW LEVEL SECURITY;