-- Fund Requests — Phase 4: permitir que cualquier staff vinculado vea
-- las work_orders APROBADAS, para poder asociarlas a una solicitud de fondos.
--
-- Antes de esto, solo team_members del engagement o admins veían las OTs.
-- Eso bloqueaba a los solicitantes que no son partner/manager (rol staff,
-- senior, semisenior, etc.) — que es justamente el caso de uso normal del
-- módulo de Solicitudes de Fondos.
--
-- IMPORTANTE:
-- - Solo abre SELECT, no INSERT/UPDATE/DELETE.
-- - Solo abre OTs en estado 'Approved' (las Draft/Pending/Rejected siguen
--   restringidas a team_members + admin).
-- - Requiere staff vinculado (get_my_staff_id() IS NOT NULL) para evitar
--   exponer datos a cuentas auth sin staff.

-- NOTA: esta policy amplia exponía cliente/NIT/presupuesto/notas de TODAS las
-- OTs aprobadas a cualquier staff (vía useWorkOrders → select *). Se REEMPLAZÓ
-- por un acceso acotado en 20260610190000_fund_request_wo_safe_access.sql:
--   - vista segura `fund_request_selectable_work_orders` para el dropdown, y
--   - policy angosta `wo_in_my_fund_request` para el embed.
-- Aquí solo se asegura que la policy amplia NO exista.
DROP POLICY IF EXISTS "Staff can view approved work orders" ON public.work_orders;
