-- Seed del catalogo de notificaciones: 76 tipos, 464 concesiones rol x tipo.
-- Archivo generado a partir de la matriz de notificaciones. Idempotente.

insert into public.notification_types
  (type_key, module_key, label_key, delivery, display_order, is_active, email_enabled) values
  ('auth.account.email', 'auth', 'notifications.types.auth.account.email', 'email', 1, true, false),
  ('auth.user.registered', 'auth', 'notifications.types.auth.user.registered', 'event', 2, true, false),
  ('auth.role.changed', 'auth', 'notifications.types.auth.role.changed', 'event', 3, true, true),
  ('auth.account.blocked', 'auth', 'notifications.types.auth.account.blocked', 'event', 4, true, false),
  ('auth.account.deleted', 'auth', 'notifications.types.auth.account.deleted', 'event', 5, true, false),
  ('staff.created', 'auth', 'notifications.types.staff.created', 'event', 6, true, false),
  ('staff.terminated', 'auth', 'notifications.types.staff.terminated', 'event', 7, true, false),
  ('staff.competency.assigned', 'auth', 'notifications.types.staff.competency.assigned', 'event', 8, true, false),
  ('staff.competency.removed', 'auth', 'notifications.types.staff.competency.removed', 'event', 9, true, false),
  ('client.created', 'client', 'notifications.types.client.created', 'event', 10, true, false),
  ('client.updated', 'client', 'notifications.types.client.updated', 'event', 11, true, false),
  ('client.deactivated', 'client', 'notifications.types.client.deactivated', 'event', 12, true, false),
  ('engagement.created', 'engagement', 'notifications.types.engagement.created', 'event', 13, true, false),
  ('engagement.owners.changed', 'engagement', 'notifications.types.engagement.owners.changed', 'event', 14, true, false),
  ('engagement.ending_soon', 'engagement', 'notifications.types.engagement.ending_soon', 'event', 15, true, true),
  ('engagement.finalized', 'engagement', 'notifications.types.engagement.finalized', 'event', 16, true, false),
  ('engagement.deleted', 'engagement', 'notifications.types.engagement.deleted', 'event', 17, true, false),
  ('engagement.sqr_assigned', 'engagement', 'notifications.types.engagement.sqr_assigned', 'event', 18, true, true),
  ('engagement.encargado_assigned', 'engagement', 'notifications.types.engagement.encargado_assigned', 'event', 19, true, true),
  ('engagement.specialist_assigned', 'engagement', 'notifications.types.engagement.specialist_assigned', 'event', 20, true, true),
  ('engagement.staffing.changed', 'engagement', 'notifications.types.engagement.staffing.changed', 'event', 21, true, false),
  ('worksheet.sent_to_quality', 'worksheet', 'notifications.types.worksheet.sent_to_quality', 'event', 22, true, false),
  ('wo.submitted_partner', 'work_order', 'notifications.types.wo.submitted_partner', 'event', 23, true, true),
  ('wo.submitted_risk', 'work_order', 'notifications.types.wo.submitted_risk', 'event', 24, true, true),
  ('wo.approved_partner', 'work_order', 'notifications.types.wo.approved_partner', 'event', 25, true, false),
  ('wo.rejected_partner', 'work_order', 'notifications.types.wo.rejected_partner', 'event', 26, true, true),
  ('wo.approved_risk', 'work_order', 'notifications.types.wo.approved_risk', 'event', 27, true, false),
  ('wo.rejected_risk', 'work_order', 'notifications.types.wo.rejected_risk', 'event', 28, true, true),
  ('wo.approval_reverted', 'work_order', 'notifications.types.wo.approval_reverted', 'event', 29, true, true),
  ('wo.emergency.created', 'work_order', 'notifications.types.wo.emergency.created', 'event', 30, true, false),
  ('wo.emergency.step1_done', 'work_order', 'notifications.types.wo.emergency.step1_done', 'event', 31, true, false),
  ('wo.emergency.deadline_near', 'work_order', 'notifications.types.wo.emergency.deadline_near', 'event', 32, true, true),
  ('wo.emergency.deadline_passed', 'work_order', 'notifications.types.wo.emergency.deadline_passed', 'event', 33, true, true),
  ('wo.risk.resubmitted', 'work_order', 'notifications.types.wo.risk.resubmitted', 'event', 34, true, true),
  ('wo.payment_plan.pending_approval', 'work_order', 'notifications.types.wo.payment_plan.pending_approval', 'event', 35, true, true),
  ('wo.installment.status_changed', 'work_order', 'notifications.types.wo.installment.status_changed', 'event', 36, true, false),
  ('wo.installment.due_this_week', 'work_order', 'notifications.types.wo.installment.due_this_week', 'aggregate', 37, true, false),
  ('wo.installment.overdue', 'work_order', 'notifications.types.wo.installment.overdue', 'aggregate', 38, true, false),
  ('wo.client.billing_week', 'work_order', 'notifications.types.wo.client.billing_week', 'event', 39, true, false),
  ('fund.request.submitted_for_approval', 'fund_request', 'notifications.types.fund.request.submitted_for_approval', 'event', 40, true, true),
  ('fund.expense.submitted_for_approval', 'fund_request', 'notifications.types.fund.expense.submitted_for_approval', 'event', 41, true, false),
  ('fund.request.cancelled', 'fund_request', 'notifications.types.fund.request.cancelled', 'event', 42, true, true),
  ('fund.request.decided', 'fund_request', 'notifications.types.fund.request.decided', 'event', 43, true, true),
  ('fund.disbursement.done', 'fund_request', 'notifications.types.fund.disbursement.done', 'event', 44, true, true),
  ('fund.settlement.recorded', 'fund_request', 'notifications.types.fund.settlement.recorded', 'event', 45, true, true),
  ('fund.request.closed', 'fund_request', 'notifications.types.fund.request.closed', 'event', 46, true, true),
  ('fund.expense.returned_no_support', 'fund_request', 'notifications.types.fund.expense.returned_no_support', 'event', 47, true, true),
  ('fund.expense.decided', 'fund_request', 'notifications.types.fund.expense.decided', 'event', 48, true, false),
  ('fund.expense.reviewed', 'fund_request', 'notifications.types.fund.expense.reviewed', 'event', 49, true, false),
  ('fund.expenses.all_reviewed', 'fund_request', 'notifications.types.fund.expenses.all_reviewed', 'event', 50, true, true),
  ('fund.expense.iva_penalty', 'fund_request', 'notifications.types.fund.expense.iva_penalty', 'event', 51, true, true),
  ('fund.expense.review_pending', 'fund_request', 'notifications.types.fund.expense.review_pending', 'aggregate', 52, true, false),
  ('fund.settlement.pending', 'fund_request', 'notifications.types.fund.settlement.pending', 'aggregate', 53, true, false),
  ('fund.request.closure_pending', 'fund_request', 'notifications.types.fund.request.closure_pending', 'aggregate', 54, true, false),
  ('fund.disbursement.pending', 'fund_request', 'notifications.types.fund.disbursement.pending', 'aggregate', 55, true, false),
  ('fund.expense.sent_to_support_review', 'fund_request', 'notifications.types.fund.expense.sent_to_support_review', 'event', 56, true, false),
  ('fund.expense.resubmitted', 'fund_request', 'notifications.types.fund.expense.resubmitted', 'event', 57, true, false),
  ('timesheet.weekly_submitted', 'timesheet', 'notifications.types.timesheet.weekly_submitted', 'event', 58, true, false),
  ('timesheet.own_submit_confirmed', 'timesheet', 'notifications.types.timesheet.own_submit_confirmed', 'event', 59, true, true),
  ('timesheet.team_submitted_for_approval', 'timesheet', 'notifications.types.timesheet.team_submitted_for_approval', 'event', 60, true, false),
  ('timesheet.overdue', 'timesheet', 'notifications.types.timesheet.overdue', 'aggregate', 61, true, false),
  ('timesheet.reverted', 'timesheet', 'notifications.types.timesheet.reverted', 'aggregate', 62, true, false),
  ('timesheet.pending_approval', 'timesheet', 'notifications.types.timesheet.pending_approval', 'aggregate', 63, true, false),
  ('tracker.timer.auto_stopped', 'tracker', 'notifications.types.tracker.timer.auto_stopped', 'event', 64, true, false),
  ('approval.line_approved', 'timesheet_approval', 'notifications.types.approval.line_approved', 'event', 65, true, false),
  ('approval.line_rejected', 'timesheet_approval', 'notifications.types.approval.line_rejected', 'event', 66, true, false),
  ('approval.revision_requested', 'timesheet_approval', 'notifications.types.approval.revision_requested', 'event', 67, true, false),
  ('approval.training_pending', 'timesheet_approval', 'notifications.types.approval.training_pending', 'aggregate', 68, true, false),
  ('engagement.rejected_by_partner', 'engagement', 'notifications.types.engagement.rejected_by_partner', 'aggregate', 69, true, false),
  ('engagement.pending_partner_approval', 'engagement', 'notifications.types.engagement.pending_partner_approval', 'aggregate', 70, true, false),
  ('scheduler.coverage_gap', 'scheduler', 'notifications.types.scheduler.coverage_gap', 'aggregate', 71, true, false),
  ('scheduler.own_assignment_changed', 'scheduler', 'notifications.types.scheduler.own_assignment_changed', 'event', 72, true, false),
  ('timesheet.reminder.daily', 'timesheet', 'notifications.types.timesheet.reminder.daily', 'email', 73, true, true),
  ('approval.reminder.weekly', 'timesheet_approval', 'notifications.types.approval.reminder.weekly', 'email', 74, true, true),
  ('fund.reminder.weekly', 'fund_request', 'notifications.types.fund.reminder.weekly', 'email', 75, true, true),
  ('wo.installment.reminder.weekly', 'work_order', 'notifications.types.wo.installment.reminder.weekly', 'email', 76, true, true)
on conflict (type_key) do update set
  module_key    = excluded.module_key,
  label_key     = excluded.label_key,
  delivery      = excluded.delivery,
  display_order = excluded.display_order,
  is_active     = excluded.is_active,
  email_enabled = excluded.email_enabled;

insert into public.notification_role_types (role_key, type_key, scope_key) values
  ('admin', 'auth.account.email', 'own'),
  ('it_security_manager', 'auth.account.email', 'own'),
  ('senior_partner', 'auth.account.email', 'own'),
  ('partner', 'auth.account.email', 'own'),
  ('sqr', 'auth.account.email', 'own'),
  ('director', 'auth.account.email', 'own'),
  ('manager', 'auth.account.email', 'own'),
  ('senior', 'auth.account.email', 'own'),
  ('semisenior', 'auth.account.email', 'own'),
  ('assistant', 'auth.account.email', 'own'),
  ('ita_manager', 'auth.account.email', 'own'),
  ('ita_senior', 'auth.account.email', 'own'),
  ('ita_assistant', 'auth.account.email', 'own'),
  ('tax_manager', 'auth.account.email', 'own'),
  ('tax_senior', 'auth.account.email', 'own'),
  ('tax_assistant', 'auth.account.email', 'own'),
  ('accounting_manager', 'auth.account.email', 'own'),
  ('accounting_analyst', 'auth.account.email', 'own'),
  ('collections_analyst', 'auth.account.email', 'own'),
  ('risk_partner', 'auth.account.email', 'own'),
  ('risk_supervisor', 'auth.account.email', 'own'),
  ('hr_manager', 'auth.account.email', 'own'),
  ('hr_analyst', 'auth.account.email', 'own'),
  ('admin', 'auth.user.registered', 'firm'),
  ('admin', 'auth.role.changed', 'firm'),
  ('it_security_manager', 'auth.role.changed', 'firm'),
  ('senior_partner', 'auth.role.changed', 'own'),
  ('partner', 'auth.role.changed', 'own'),
  ('sqr', 'auth.role.changed', 'own'),
  ('director', 'auth.role.changed', 'own'),
  ('manager', 'auth.role.changed', 'own'),
  ('senior', 'auth.role.changed', 'own'),
  ('semisenior', 'auth.role.changed', 'own'),
  ('assistant', 'auth.role.changed', 'own'),
  ('ita_manager', 'auth.role.changed', 'own'),
  ('ita_senior', 'auth.role.changed', 'own'),
  ('ita_assistant', 'auth.role.changed', 'own'),
  ('tax_manager', 'auth.role.changed', 'own'),
  ('tax_senior', 'auth.role.changed', 'own'),
  ('tax_assistant', 'auth.role.changed', 'own'),
  ('accounting_manager', 'auth.role.changed', 'own'),
  ('accounting_analyst', 'auth.role.changed', 'own'),
  ('collections_analyst', 'auth.role.changed', 'own'),
  ('risk_partner', 'auth.role.changed', 'own'),
  ('risk_supervisor', 'auth.role.changed', 'own'),
  ('hr_manager', 'auth.role.changed', 'own'),
  ('hr_analyst', 'auth.role.changed', 'own'),
  ('admin', 'auth.account.blocked', 'firm'),
  ('it_security_manager', 'auth.account.blocked', 'firm'),
  ('it_security_manager', 'auth.account.deleted', 'firm'),
  ('admin', 'staff.created', 'firm'),
  ('manager', 'staff.created', 'practice'),
  ('ita_manager', 'staff.created', 'practice'),
  ('tax_manager', 'staff.created', 'practice'),
  ('hr_manager', 'staff.created', 'firm'),
  ('hr_analyst', 'staff.created', 'firm'),
  ('admin', 'staff.terminated', 'firm'),
  ('manager', 'staff.terminated', 'practice'),
  ('ita_manager', 'staff.terminated', 'practice'),
  ('tax_manager', 'staff.terminated', 'practice'),
  ('hr_manager', 'staff.terminated', 'firm'),
  ('hr_analyst', 'staff.terminated', 'firm'),
  ('senior', 'staff.competency.assigned', 'own'),
  ('semisenior', 'staff.competency.assigned', 'own'),
  ('assistant', 'staff.competency.assigned', 'own'),
  ('ita_senior', 'staff.competency.assigned', 'own'),
  ('ita_assistant', 'staff.competency.assigned', 'own'),
  ('tax_senior', 'staff.competency.assigned', 'own'),
  ('tax_assistant', 'staff.competency.assigned', 'own'),
  ('senior', 'staff.competency.removed', 'own'),
  ('semisenior', 'staff.competency.removed', 'own'),
  ('assistant', 'staff.competency.removed', 'own'),
  ('ita_senior', 'staff.competency.removed', 'own'),
  ('ita_assistant', 'staff.competency.removed', 'own'),
  ('tax_senior', 'staff.competency.removed', 'own'),
  ('tax_assistant', 'staff.competency.removed', 'own'),
  ('senior_partner', 'client.created', 'firm'),
  ('manager', 'client.created', 'assigned'),
  ('ita_manager', 'client.created', 'assigned'),
  ('tax_manager', 'client.created', 'assigned'),
  ('manager', 'client.updated', 'assigned'),
  ('ita_manager', 'client.updated', 'assigned'),
  ('tax_manager', 'client.updated', 'assigned'),
  ('senior_partner', 'client.deactivated', 'firm'),
  ('partner', 'client.deactivated', 'assigned'),
  ('director', 'client.deactivated', 'assigned'),
  ('manager', 'client.deactivated', 'assigned'),
  ('ita_manager', 'client.deactivated', 'assigned'),
  ('tax_manager', 'client.deactivated', 'assigned'),
  ('senior_partner', 'engagement.created', 'assigned'),
  ('partner', 'engagement.created', 'assigned'),
  ('director', 'engagement.created', 'assigned'),
  ('manager', 'engagement.created', 'assigned'),
  ('ita_manager', 'engagement.created', 'assigned'),
  ('tax_manager', 'engagement.created', 'assigned'),
  ('risk_partner', 'engagement.created', 'assigned'),
  ('admin', 'engagement.owners.changed', 'firm'),
  ('senior_partner', 'engagement.owners.changed', 'assigned'),
  ('partner', 'engagement.owners.changed', 'assigned'),
  ('director', 'engagement.owners.changed', 'assigned'),
  ('manager', 'engagement.owners.changed', 'assigned'),
  ('ita_manager', 'engagement.owners.changed', 'assigned'),
  ('tax_manager', 'engagement.owners.changed', 'assigned'),
  ('risk_partner', 'engagement.owners.changed', 'assigned'),
  ('admin', 'engagement.ending_soon', 'firm'),
  ('senior_partner', 'engagement.ending_soon', 'assigned'),
  ('partner', 'engagement.ending_soon', 'assigned'),
  ('sqr', 'engagement.ending_soon', 'assigned'),
  ('director', 'engagement.ending_soon', 'assigned'),
  ('manager', 'engagement.ending_soon', 'assigned'),
  ('ita_manager', 'engagement.ending_soon', 'assigned'),
  ('tax_manager', 'engagement.ending_soon', 'assigned'),
  ('admin', 'engagement.finalized', 'firm'),
  ('senior_partner', 'engagement.finalized', 'assigned'),
  ('partner', 'engagement.finalized', 'assigned'),
  ('director', 'engagement.finalized', 'assigned'),
  ('manager', 'engagement.finalized', 'assigned'),
  ('senior', 'engagement.finalized', 'assigned'),
  ('semisenior', 'engagement.finalized', 'assigned'),
  ('assistant', 'engagement.finalized', 'assigned'),
  ('ita_manager', 'engagement.finalized', 'assigned'),
  ('ita_senior', 'engagement.finalized', 'assigned'),
  ('ita_assistant', 'engagement.finalized', 'assigned'),
  ('tax_manager', 'engagement.finalized', 'assigned'),
  ('tax_senior', 'engagement.finalized', 'assigned'),
  ('tax_assistant', 'engagement.finalized', 'assigned'),
  ('risk_partner', 'engagement.finalized', 'assigned'),
  ('admin', 'engagement.deleted', 'firm'),
  ('senior_partner', 'engagement.sqr_assigned', 'own'),
  ('partner', 'engagement.sqr_assigned', 'own'),
  ('director', 'engagement.sqr_assigned', 'own'),
  ('senior', 'engagement.sqr_assigned', 'own'),
  ('senior', 'engagement.encargado_assigned', 'own'),
  ('semisenior', 'engagement.encargado_assigned', 'own'),
  ('ita_senior', 'engagement.encargado_assigned', 'own'),
  ('tax_senior', 'engagement.encargado_assigned', 'own'),
  ('ita_manager', 'engagement.specialist_assigned', 'own'),
  ('tax_manager', 'engagement.specialist_assigned', 'own'),
  ('manager', 'engagement.staffing.changed', 'assigned'),
  ('senior', 'engagement.staffing.changed', 'own'),
  ('semisenior', 'engagement.staffing.changed', 'own'),
  ('assistant', 'engagement.staffing.changed', 'own'),
  ('ita_manager', 'engagement.staffing.changed', 'assigned'),
  ('ita_senior', 'engagement.staffing.changed', 'own'),
  ('ita_assistant', 'engagement.staffing.changed', 'own'),
  ('tax_manager', 'engagement.staffing.changed', 'assigned'),
  ('tax_senior', 'engagement.staffing.changed', 'own'),
  ('tax_assistant', 'engagement.staffing.changed', 'own'),
  ('senior_partner', 'worksheet.sent_to_quality', 'assigned'),
  ('partner', 'worksheet.sent_to_quality', 'assigned'),
  ('sqr', 'worksheet.sent_to_quality', 'assigned'),
  ('director', 'worksheet.sent_to_quality', 'assigned'),
  ('senior', 'worksheet.sent_to_quality', 'assigned'),
  ('senior_partner', 'wo.submitted_partner', 'assigned'),
  ('partner', 'wo.submitted_partner', 'assigned'),
  ('sqr', 'wo.submitted_partner', 'assigned'),
  ('director', 'wo.submitted_partner', 'assigned'),
  ('senior', 'wo.submitted_partner', 'assigned'),
  ('risk_partner', 'wo.submitted_risk', 'department'),
  ('risk_supervisor', 'wo.submitted_risk', 'department'),
  ('manager', 'wo.approved_partner', 'assigned'),
  ('ita_manager', 'wo.approved_partner', 'assigned'),
  ('tax_manager', 'wo.approved_partner', 'assigned'),
  ('manager', 'wo.rejected_partner', 'assigned'),
  ('ita_manager', 'wo.rejected_partner', 'assigned'),
  ('tax_manager', 'wo.rejected_partner', 'assigned'),
  ('manager', 'wo.approved_risk', 'assigned'),
  ('ita_manager', 'wo.approved_risk', 'assigned'),
  ('tax_manager', 'wo.approved_risk', 'assigned'),
  ('senior_partner', 'wo.rejected_risk', 'assigned'),
  ('partner', 'wo.rejected_risk', 'assigned'),
  ('director', 'wo.rejected_risk', 'assigned'),
  ('manager', 'wo.rejected_risk', 'assigned'),
  ('ita_manager', 'wo.rejected_risk', 'assigned'),
  ('tax_manager', 'wo.rejected_risk', 'assigned'),
  ('senior_partner', 'wo.approval_reverted', 'assigned'),
  ('partner', 'wo.approval_reverted', 'assigned'),
  ('director', 'wo.approval_reverted', 'assigned'),
  ('manager', 'wo.approval_reverted', 'assigned'),
  ('ita_manager', 'wo.approval_reverted', 'assigned'),
  ('tax_manager', 'wo.approval_reverted', 'assigned'),
  ('manager', 'wo.emergency.created', 'assigned'),
  ('ita_manager', 'wo.emergency.created', 'assigned'),
  ('tax_manager', 'wo.emergency.created', 'assigned'),
  ('risk_partner', 'wo.emergency.step1_done', 'department'),
  ('admin', 'wo.emergency.deadline_near', 'firm'),
  ('manager', 'wo.emergency.deadline_near', 'assigned'),
  ('ita_manager', 'wo.emergency.deadline_near', 'assigned'),
  ('tax_manager', 'wo.emergency.deadline_near', 'assigned'),
  ('risk_supervisor', 'wo.emergency.deadline_passed', 'department'),
  ('risk_supervisor', 'wo.risk.resubmitted', 'department'),
  ('senior_partner', 'wo.payment_plan.pending_approval', 'assigned'),
  ('partner', 'wo.payment_plan.pending_approval', 'assigned'),
  ('sqr', 'wo.payment_plan.pending_approval', 'assigned'),
  ('director', 'wo.payment_plan.pending_approval', 'assigned'),
  ('senior', 'wo.payment_plan.pending_approval', 'assigned'),
  ('collections_analyst', 'wo.payment_plan.pending_approval', 'department'),
  ('accounting_manager', 'wo.installment.status_changed', 'department'),
  ('accounting_analyst', 'wo.installment.status_changed', 'department'),
  ('accounting_manager', 'wo.installment.due_this_week', 'department'),
  ('accounting_analyst', 'wo.installment.due_this_week', 'department'),
  ('manager', 'wo.installment.overdue', 'assigned'),
  ('ita_manager', 'wo.installment.overdue', 'assigned'),
  ('tax_manager', 'wo.installment.overdue', 'assigned'),
  ('accounting_manager', 'wo.installment.overdue', 'department'),
  ('accounting_analyst', 'wo.installment.overdue', 'department'),
  ('collections_analyst', 'wo.installment.overdue', 'department'),
  ('manager', 'wo.client.billing_week', 'assigned'),
  ('ita_manager', 'wo.client.billing_week', 'assigned'),
  ('tax_manager', 'wo.client.billing_week', 'assigned'),
  ('manager', 'fund.request.submitted_for_approval', 'assigned'),
  ('ita_manager', 'fund.request.submitted_for_approval', 'assigned'),
  ('tax_manager', 'fund.request.submitted_for_approval', 'assigned'),
  ('manager', 'fund.expense.submitted_for_approval', 'assigned'),
  ('ita_manager', 'fund.expense.submitted_for_approval', 'assigned'),
  ('tax_manager', 'fund.expense.submitted_for_approval', 'assigned'),
  ('admin', 'fund.request.cancelled', 'firm'),
  ('manager', 'fund.request.cancelled', 'assigned'),
  ('ita_manager', 'fund.request.cancelled', 'assigned'),
  ('tax_manager', 'fund.request.cancelled', 'assigned'),
  ('senior', 'fund.request.decided', 'own'),
  ('semisenior', 'fund.request.decided', 'own'),
  ('assistant', 'fund.request.decided', 'own'),
  ('ita_senior', 'fund.request.decided', 'own'),
  ('ita_assistant', 'fund.request.decided', 'own'),
  ('tax_senior', 'fund.request.decided', 'own'),
  ('tax_assistant', 'fund.request.decided', 'own'),
  ('accounting_analyst', 'fund.request.decided', 'own'),
  ('collections_analyst', 'fund.request.decided', 'own'),
  ('manager', 'fund.disbursement.done', 'assigned'),
  ('senior', 'fund.disbursement.done', 'own'),
  ('semisenior', 'fund.disbursement.done', 'own'),
  ('assistant', 'fund.disbursement.done', 'own'),
  ('ita_manager', 'fund.disbursement.done', 'assigned'),
  ('ita_senior', 'fund.disbursement.done', 'own'),
  ('ita_assistant', 'fund.disbursement.done', 'own'),
  ('tax_manager', 'fund.disbursement.done', 'assigned'),
  ('tax_senior', 'fund.disbursement.done', 'own'),
  ('tax_assistant', 'fund.disbursement.done', 'own'),
  ('manager', 'fund.settlement.recorded', 'assigned'),
  ('senior', 'fund.settlement.recorded', 'own'),
  ('semisenior', 'fund.settlement.recorded', 'own'),
  ('assistant', 'fund.settlement.recorded', 'own'),
  ('ita_manager', 'fund.settlement.recorded', 'assigned'),
  ('ita_senior', 'fund.settlement.recorded', 'own'),
  ('ita_assistant', 'fund.settlement.recorded', 'own'),
  ('tax_manager', 'fund.settlement.recorded', 'assigned'),
  ('tax_senior', 'fund.settlement.recorded', 'own'),
  ('tax_assistant', 'fund.settlement.recorded', 'own'),
  ('manager', 'fund.request.closed', 'assigned'),
  ('senior', 'fund.request.closed', 'own'),
  ('semisenior', 'fund.request.closed', 'own'),
  ('assistant', 'fund.request.closed', 'own'),
  ('ita_manager', 'fund.request.closed', 'assigned'),
  ('ita_senior', 'fund.request.closed', 'own'),
  ('ita_assistant', 'fund.request.closed', 'own'),
  ('tax_manager', 'fund.request.closed', 'assigned'),
  ('tax_senior', 'fund.request.closed', 'own'),
  ('tax_assistant', 'fund.request.closed', 'own'),
  ('senior', 'fund.expense.returned_no_support', 'own'),
  ('semisenior', 'fund.expense.returned_no_support', 'own'),
  ('assistant', 'fund.expense.returned_no_support', 'own'),
  ('ita_senior', 'fund.expense.returned_no_support', 'own'),
  ('ita_assistant', 'fund.expense.returned_no_support', 'own'),
  ('tax_senior', 'fund.expense.returned_no_support', 'own'),
  ('tax_assistant', 'fund.expense.returned_no_support', 'own'),
  ('senior', 'fund.expense.decided', 'own'),
  ('semisenior', 'fund.expense.decided', 'own'),
  ('assistant', 'fund.expense.decided', 'own'),
  ('ita_senior', 'fund.expense.decided', 'own'),
  ('ita_assistant', 'fund.expense.decided', 'own'),
  ('tax_senior', 'fund.expense.decided', 'own'),
  ('tax_assistant', 'fund.expense.decided', 'own'),
  ('senior', 'fund.expense.reviewed', 'own'),
  ('semisenior', 'fund.expense.reviewed', 'own'),
  ('assistant', 'fund.expense.reviewed', 'own'),
  ('ita_senior', 'fund.expense.reviewed', 'own'),
  ('ita_assistant', 'fund.expense.reviewed', 'own'),
  ('tax_senior', 'fund.expense.reviewed', 'own'),
  ('tax_assistant', 'fund.expense.reviewed', 'own'),
  ('manager', 'fund.expenses.all_reviewed', 'assigned'),
  ('ita_manager', 'fund.expenses.all_reviewed', 'assigned'),
  ('tax_manager', 'fund.expenses.all_reviewed', 'assigned'),
  ('senior', 'fund.expense.iva_penalty', 'own'),
  ('semisenior', 'fund.expense.iva_penalty', 'own'),
  ('assistant', 'fund.expense.iva_penalty', 'own'),
  ('ita_senior', 'fund.expense.iva_penalty', 'own'),
  ('ita_assistant', 'fund.expense.iva_penalty', 'own'),
  ('tax_senior', 'fund.expense.iva_penalty', 'own'),
  ('tax_assistant', 'fund.expense.iva_penalty', 'own'),
  ('accounting_manager', 'fund.expense.review_pending', 'department'),
  ('accounting_analyst', 'fund.expense.review_pending', 'department'),
  ('accounting_manager', 'fund.settlement.pending', 'department'),
  ('accounting_manager', 'fund.request.closure_pending', 'department'),
  ('accounting_manager', 'fund.disbursement.pending', 'department'),
  ('accounting_manager', 'fund.expense.sent_to_support_review', 'department'),
  ('accounting_analyst', 'fund.expense.sent_to_support_review', 'department'),
  ('accounting_manager', 'fund.expense.resubmitted', 'department'),
  ('accounting_analyst', 'fund.expense.resubmitted', 'department'),
  ('senior_partner', 'timesheet.weekly_submitted', 'assigned'),
  ('partner', 'timesheet.weekly_submitted', 'assigned'),
  ('director', 'timesheet.weekly_submitted', 'assigned'),
  ('manager', 'timesheet.weekly_submitted', 'assigned'),
  ('ita_manager', 'timesheet.weekly_submitted', 'assigned'),
  ('tax_manager', 'timesheet.weekly_submitted', 'assigned'),
  ('senior', 'timesheet.own_submit_confirmed', 'own'),
  ('semisenior', 'timesheet.own_submit_confirmed', 'own'),
  ('assistant', 'timesheet.own_submit_confirmed', 'own'),
  ('ita_senior', 'timesheet.own_submit_confirmed', 'own'),
  ('ita_assistant', 'timesheet.own_submit_confirmed', 'own'),
  ('tax_senior', 'timesheet.own_submit_confirmed', 'own'),
  ('tax_assistant', 'timesheet.own_submit_confirmed', 'own'),
  ('senior_partner', 'timesheet.team_submitted_for_approval', 'assigned'),
  ('partner', 'timesheet.team_submitted_for_approval', 'assigned'),
  ('sqr', 'timesheet.team_submitted_for_approval', 'assigned'),
  ('director', 'timesheet.team_submitted_for_approval', 'assigned'),
  ('manager', 'timesheet.team_submitted_for_approval', 'assigned'),
  ('senior', 'timesheet.team_submitted_for_approval', 'assigned'),
  ('ita_manager', 'timesheet.team_submitted_for_approval', 'assigned'),
  ('tax_manager', 'timesheet.team_submitted_for_approval', 'assigned'),
  ('it_security_manager', 'timesheet.overdue', 'own'),
  ('senior_partner', 'timesheet.overdue', 'own'),
  ('partner', 'timesheet.overdue', 'own'),
  ('sqr', 'timesheet.overdue', 'own'),
  ('director', 'timesheet.overdue', 'own'),
  ('manager', 'timesheet.overdue', 'own'),
  ('senior', 'timesheet.overdue', 'own'),
  ('semisenior', 'timesheet.overdue', 'own'),
  ('assistant', 'timesheet.overdue', 'own'),
  ('ita_manager', 'timesheet.overdue', 'own'),
  ('ita_senior', 'timesheet.overdue', 'own'),
  ('ita_assistant', 'timesheet.overdue', 'own'),
  ('tax_manager', 'timesheet.overdue', 'own'),
  ('tax_senior', 'timesheet.overdue', 'own'),
  ('tax_assistant', 'timesheet.overdue', 'own'),
  ('risk_partner', 'timesheet.overdue', 'own'),
  ('it_security_manager', 'timesheet.reverted', 'own'),
  ('senior_partner', 'timesheet.reverted', 'own'),
  ('partner', 'timesheet.reverted', 'own'),
  ('sqr', 'timesheet.reverted', 'own'),
  ('director', 'timesheet.reverted', 'own'),
  ('manager', 'timesheet.reverted', 'own'),
  ('senior', 'timesheet.reverted', 'own'),
  ('semisenior', 'timesheet.reverted', 'own'),
  ('assistant', 'timesheet.reverted', 'own'),
  ('ita_manager', 'timesheet.reverted', 'own'),
  ('ita_senior', 'timesheet.reverted', 'own'),
  ('ita_assistant', 'timesheet.reverted', 'own'),
  ('tax_manager', 'timesheet.reverted', 'own'),
  ('tax_senior', 'timesheet.reverted', 'own'),
  ('tax_assistant', 'timesheet.reverted', 'own'),
  ('risk_partner', 'timesheet.reverted', 'own'),
  ('it_security_manager', 'timesheet.pending_approval', 'own'),
  ('senior_partner', 'timesheet.pending_approval', 'own'),
  ('partner', 'timesheet.pending_approval', 'own'),
  ('sqr', 'timesheet.pending_approval', 'own'),
  ('director', 'timesheet.pending_approval', 'own'),
  ('manager', 'timesheet.pending_approval', 'own'),
  ('senior', 'timesheet.pending_approval', 'own'),
  ('semisenior', 'timesheet.pending_approval', 'own'),
  ('assistant', 'timesheet.pending_approval', 'own'),
  ('ita_manager', 'timesheet.pending_approval', 'own'),
  ('ita_senior', 'timesheet.pending_approval', 'own'),
  ('ita_assistant', 'timesheet.pending_approval', 'own'),
  ('tax_manager', 'timesheet.pending_approval', 'own'),
  ('tax_senior', 'timesheet.pending_approval', 'own'),
  ('tax_assistant', 'timesheet.pending_approval', 'own'),
  ('risk_partner', 'timesheet.pending_approval', 'own'),
  ('senior', 'tracker.timer.auto_stopped', 'own'),
  ('semisenior', 'tracker.timer.auto_stopped', 'own'),
  ('assistant', 'tracker.timer.auto_stopped', 'own'),
  ('ita_senior', 'tracker.timer.auto_stopped', 'own'),
  ('ita_assistant', 'tracker.timer.auto_stopped', 'own'),
  ('tax_senior', 'tracker.timer.auto_stopped', 'own'),
  ('tax_assistant', 'tracker.timer.auto_stopped', 'own'),
  ('senior', 'approval.line_approved', 'own'),
  ('semisenior', 'approval.line_approved', 'own'),
  ('assistant', 'approval.line_approved', 'own'),
  ('ita_senior', 'approval.line_approved', 'own'),
  ('ita_assistant', 'approval.line_approved', 'own'),
  ('tax_senior', 'approval.line_approved', 'own'),
  ('tax_assistant', 'approval.line_approved', 'own'),
  ('senior', 'approval.line_rejected', 'own'),
  ('semisenior', 'approval.line_rejected', 'own'),
  ('assistant', 'approval.line_rejected', 'own'),
  ('ita_senior', 'approval.line_rejected', 'own'),
  ('ita_assistant', 'approval.line_rejected', 'own'),
  ('tax_senior', 'approval.line_rejected', 'own'),
  ('tax_assistant', 'approval.line_rejected', 'own'),
  ('senior', 'approval.revision_requested', 'own'),
  ('semisenior', 'approval.revision_requested', 'own'),
  ('assistant', 'approval.revision_requested', 'own'),
  ('ita_senior', 'approval.revision_requested', 'own'),
  ('ita_assistant', 'approval.revision_requested', 'own'),
  ('tax_senior', 'approval.revision_requested', 'own'),
  ('tax_assistant', 'approval.revision_requested', 'own'),
  ('admin', 'approval.training_pending', 'firm'),
  ('hr_manager', 'approval.training_pending', 'department'),
  ('hr_analyst', 'approval.training_pending', 'department'),
  ('manager', 'engagement.rejected_by_partner', 'assigned'),
  ('ita_manager', 'engagement.rejected_by_partner', 'assigned'),
  ('tax_manager', 'engagement.rejected_by_partner', 'assigned'),
  ('manager', 'engagement.pending_partner_approval', 'assigned'),
  ('ita_manager', 'engagement.pending_partner_approval', 'assigned'),
  ('tax_manager', 'engagement.pending_partner_approval', 'assigned'),
  ('admin', 'scheduler.coverage_gap', 'firm'),
  ('senior_partner', 'scheduler.coverage_gap', 'firm'),
  ('partner', 'scheduler.coverage_gap', 'society'),
  ('sqr', 'scheduler.coverage_gap', 'assigned'),
  ('director', 'scheduler.coverage_gap', 'assigned'),
  ('manager', 'scheduler.coverage_gap', 'assigned'),
  ('senior', 'scheduler.coverage_gap', 'assigned'),
  ('ita_manager', 'scheduler.coverage_gap', 'assigned'),
  ('tax_manager', 'scheduler.coverage_gap', 'assigned'),
  ('senior', 'scheduler.own_assignment_changed', 'own'),
  ('semisenior', 'scheduler.own_assignment_changed', 'own'),
  ('assistant', 'scheduler.own_assignment_changed', 'own'),
  ('ita_senior', 'scheduler.own_assignment_changed', 'own'),
  ('ita_assistant', 'scheduler.own_assignment_changed', 'own'),
  ('tax_senior', 'scheduler.own_assignment_changed', 'own'),
  ('tax_assistant', 'scheduler.own_assignment_changed', 'own'),
  ('it_security_manager', 'timesheet.reminder.daily', 'own'),
  ('senior_partner', 'timesheet.reminder.daily', 'own'),
  ('partner', 'timesheet.reminder.daily', 'own'),
  ('sqr', 'timesheet.reminder.daily', 'own'),
  ('director', 'timesheet.reminder.daily', 'own'),
  ('manager', 'timesheet.reminder.daily', 'own'),
  ('senior', 'timesheet.reminder.daily', 'own'),
  ('semisenior', 'timesheet.reminder.daily', 'own'),
  ('assistant', 'timesheet.reminder.daily', 'own'),
  ('ita_manager', 'timesheet.reminder.daily', 'own'),
  ('ita_senior', 'timesheet.reminder.daily', 'own'),
  ('ita_assistant', 'timesheet.reminder.daily', 'own'),
  ('tax_manager', 'timesheet.reminder.daily', 'own'),
  ('tax_senior', 'timesheet.reminder.daily', 'own'),
  ('tax_assistant', 'timesheet.reminder.daily', 'own'),
  ('risk_partner', 'timesheet.reminder.daily', 'own'),
  ('admin', 'approval.reminder.weekly', 'firm'),
  ('it_security_manager', 'approval.reminder.weekly', 'own'),
  ('senior_partner', 'approval.reminder.weekly', 'own'),
  ('partner', 'approval.reminder.weekly', 'own'),
  ('sqr', 'approval.reminder.weekly', 'own'),
  ('director', 'approval.reminder.weekly', 'own'),
  ('manager', 'approval.reminder.weekly', 'assigned'),
  ('senior', 'approval.reminder.weekly', 'own'),
  ('semisenior', 'approval.reminder.weekly', 'own'),
  ('assistant', 'approval.reminder.weekly', 'own'),
  ('ita_manager', 'approval.reminder.weekly', 'assigned'),
  ('ita_senior', 'approval.reminder.weekly', 'own'),
  ('ita_assistant', 'approval.reminder.weekly', 'own'),
  ('tax_manager', 'approval.reminder.weekly', 'assigned'),
  ('tax_senior', 'approval.reminder.weekly', 'own'),
  ('tax_assistant', 'approval.reminder.weekly', 'own'),
  ('risk_partner', 'approval.reminder.weekly', 'own'),
  ('hr_manager', 'approval.reminder.weekly', 'department'),
  ('hr_analyst', 'approval.reminder.weekly', 'department'),
  ('accounting_manager', 'fund.reminder.weekly', 'department'),
  ('accounting_analyst', 'fund.reminder.weekly', 'department'),
  ('manager', 'wo.installment.reminder.weekly', 'assigned'),
  ('ita_manager', 'wo.installment.reminder.weekly', 'assigned'),
  ('tax_manager', 'wo.installment.reminder.weekly', 'assigned'),
  ('accounting_manager', 'wo.installment.reminder.weekly', 'department'),
  ('accounting_analyst', 'wo.installment.reminder.weekly', 'department'),
  ('collections_analyst', 'wo.installment.reminder.weekly', 'department')
on conflict (role_key, type_key) do update set scope_key = excluded.scope_key;

-- Filas que ya no estan en la matriz dejan de existir en el catalogo.
delete from public.notification_role_types
 where (role_key, type_key) not in (
   ('admin', 'auth.account.email'),
   ('it_security_manager', 'auth.account.email'),
   ('senior_partner', 'auth.account.email'),
   ('partner', 'auth.account.email'),
   ('sqr', 'auth.account.email'),
   ('director', 'auth.account.email'),
   ('manager', 'auth.account.email'),
   ('senior', 'auth.account.email'),
   ('semisenior', 'auth.account.email'),
   ('assistant', 'auth.account.email'),
   ('ita_manager', 'auth.account.email'),
   ('ita_senior', 'auth.account.email'),
   ('ita_assistant', 'auth.account.email'),
   ('tax_manager', 'auth.account.email'),
   ('tax_senior', 'auth.account.email'),
   ('tax_assistant', 'auth.account.email'),
   ('accounting_manager', 'auth.account.email'),
   ('accounting_analyst', 'auth.account.email'),
   ('collections_analyst', 'auth.account.email'),
   ('risk_partner', 'auth.account.email'),
   ('risk_supervisor', 'auth.account.email'),
   ('hr_manager', 'auth.account.email'),
   ('hr_analyst', 'auth.account.email'),
   ('admin', 'auth.user.registered'),
   ('admin', 'auth.role.changed'),
   ('it_security_manager', 'auth.role.changed'),
   ('senior_partner', 'auth.role.changed'),
   ('partner', 'auth.role.changed'),
   ('sqr', 'auth.role.changed'),
   ('director', 'auth.role.changed'),
   ('manager', 'auth.role.changed'),
   ('senior', 'auth.role.changed'),
   ('semisenior', 'auth.role.changed'),
   ('assistant', 'auth.role.changed'),
   ('ita_manager', 'auth.role.changed'),
   ('ita_senior', 'auth.role.changed'),
   ('ita_assistant', 'auth.role.changed'),
   ('tax_manager', 'auth.role.changed'),
   ('tax_senior', 'auth.role.changed'),
   ('tax_assistant', 'auth.role.changed'),
   ('accounting_manager', 'auth.role.changed'),
   ('accounting_analyst', 'auth.role.changed'),
   ('collections_analyst', 'auth.role.changed'),
   ('risk_partner', 'auth.role.changed'),
   ('risk_supervisor', 'auth.role.changed'),
   ('hr_manager', 'auth.role.changed'),
   ('hr_analyst', 'auth.role.changed'),
   ('admin', 'auth.account.blocked'),
   ('it_security_manager', 'auth.account.blocked'),
   ('it_security_manager', 'auth.account.deleted'),
   ('admin', 'staff.created'),
   ('manager', 'staff.created'),
   ('ita_manager', 'staff.created'),
   ('tax_manager', 'staff.created'),
   ('hr_manager', 'staff.created'),
   ('hr_analyst', 'staff.created'),
   ('admin', 'staff.terminated'),
   ('manager', 'staff.terminated'),
   ('ita_manager', 'staff.terminated'),
   ('tax_manager', 'staff.terminated'),
   ('hr_manager', 'staff.terminated'),
   ('hr_analyst', 'staff.terminated'),
   ('senior', 'staff.competency.assigned'),
   ('semisenior', 'staff.competency.assigned'),
   ('assistant', 'staff.competency.assigned'),
   ('ita_senior', 'staff.competency.assigned'),
   ('ita_assistant', 'staff.competency.assigned'),
   ('tax_senior', 'staff.competency.assigned'),
   ('tax_assistant', 'staff.competency.assigned'),
   ('senior', 'staff.competency.removed'),
   ('semisenior', 'staff.competency.removed'),
   ('assistant', 'staff.competency.removed'),
   ('ita_senior', 'staff.competency.removed'),
   ('ita_assistant', 'staff.competency.removed'),
   ('tax_senior', 'staff.competency.removed'),
   ('tax_assistant', 'staff.competency.removed'),
   ('senior_partner', 'client.created'),
   ('manager', 'client.created'),
   ('ita_manager', 'client.created'),
   ('tax_manager', 'client.created'),
   ('manager', 'client.updated'),
   ('ita_manager', 'client.updated'),
   ('tax_manager', 'client.updated'),
   ('senior_partner', 'client.deactivated'),
   ('partner', 'client.deactivated'),
   ('director', 'client.deactivated'),
   ('manager', 'client.deactivated'),
   ('ita_manager', 'client.deactivated'),
   ('tax_manager', 'client.deactivated'),
   ('senior_partner', 'engagement.created'),
   ('partner', 'engagement.created'),
   ('director', 'engagement.created'),
   ('manager', 'engagement.created'),
   ('ita_manager', 'engagement.created'),
   ('tax_manager', 'engagement.created'),
   ('risk_partner', 'engagement.created'),
   ('admin', 'engagement.owners.changed'),
   ('senior_partner', 'engagement.owners.changed'),
   ('partner', 'engagement.owners.changed'),
   ('director', 'engagement.owners.changed'),
   ('manager', 'engagement.owners.changed'),
   ('ita_manager', 'engagement.owners.changed'),
   ('tax_manager', 'engagement.owners.changed'),
   ('risk_partner', 'engagement.owners.changed'),
   ('admin', 'engagement.ending_soon'),
   ('senior_partner', 'engagement.ending_soon'),
   ('partner', 'engagement.ending_soon'),
   ('sqr', 'engagement.ending_soon'),
   ('director', 'engagement.ending_soon'),
   ('manager', 'engagement.ending_soon'),
   ('ita_manager', 'engagement.ending_soon'),
   ('tax_manager', 'engagement.ending_soon'),
   ('admin', 'engagement.finalized'),
   ('senior_partner', 'engagement.finalized'),
   ('partner', 'engagement.finalized'),
   ('director', 'engagement.finalized'),
   ('manager', 'engagement.finalized'),
   ('senior', 'engagement.finalized'),
   ('semisenior', 'engagement.finalized'),
   ('assistant', 'engagement.finalized'),
   ('ita_manager', 'engagement.finalized'),
   ('ita_senior', 'engagement.finalized'),
   ('ita_assistant', 'engagement.finalized'),
   ('tax_manager', 'engagement.finalized'),
   ('tax_senior', 'engagement.finalized'),
   ('tax_assistant', 'engagement.finalized'),
   ('risk_partner', 'engagement.finalized'),
   ('admin', 'engagement.deleted'),
   ('senior_partner', 'engagement.sqr_assigned'),
   ('partner', 'engagement.sqr_assigned'),
   ('director', 'engagement.sqr_assigned'),
   ('senior', 'engagement.sqr_assigned'),
   ('senior', 'engagement.encargado_assigned'),
   ('semisenior', 'engagement.encargado_assigned'),
   ('ita_senior', 'engagement.encargado_assigned'),
   ('tax_senior', 'engagement.encargado_assigned'),
   ('ita_manager', 'engagement.specialist_assigned'),
   ('tax_manager', 'engagement.specialist_assigned'),
   ('manager', 'engagement.staffing.changed'),
   ('senior', 'engagement.staffing.changed'),
   ('semisenior', 'engagement.staffing.changed'),
   ('assistant', 'engagement.staffing.changed'),
   ('ita_manager', 'engagement.staffing.changed'),
   ('ita_senior', 'engagement.staffing.changed'),
   ('ita_assistant', 'engagement.staffing.changed'),
   ('tax_manager', 'engagement.staffing.changed'),
   ('tax_senior', 'engagement.staffing.changed'),
   ('tax_assistant', 'engagement.staffing.changed'),
   ('senior_partner', 'worksheet.sent_to_quality'),
   ('partner', 'worksheet.sent_to_quality'),
   ('sqr', 'worksheet.sent_to_quality'),
   ('director', 'worksheet.sent_to_quality'),
   ('senior', 'worksheet.sent_to_quality'),
   ('senior_partner', 'wo.submitted_partner'),
   ('partner', 'wo.submitted_partner'),
   ('sqr', 'wo.submitted_partner'),
   ('director', 'wo.submitted_partner'),
   ('senior', 'wo.submitted_partner'),
   ('risk_partner', 'wo.submitted_risk'),
   ('risk_supervisor', 'wo.submitted_risk'),
   ('manager', 'wo.approved_partner'),
   ('ita_manager', 'wo.approved_partner'),
   ('tax_manager', 'wo.approved_partner'),
   ('manager', 'wo.rejected_partner'),
   ('ita_manager', 'wo.rejected_partner'),
   ('tax_manager', 'wo.rejected_partner'),
   ('manager', 'wo.approved_risk'),
   ('ita_manager', 'wo.approved_risk'),
   ('tax_manager', 'wo.approved_risk'),
   ('senior_partner', 'wo.rejected_risk'),
   ('partner', 'wo.rejected_risk'),
   ('director', 'wo.rejected_risk'),
   ('manager', 'wo.rejected_risk'),
   ('ita_manager', 'wo.rejected_risk'),
   ('tax_manager', 'wo.rejected_risk'),
   ('senior_partner', 'wo.approval_reverted'),
   ('partner', 'wo.approval_reverted'),
   ('director', 'wo.approval_reverted'),
   ('manager', 'wo.approval_reverted'),
   ('ita_manager', 'wo.approval_reverted'),
   ('tax_manager', 'wo.approval_reverted'),
   ('manager', 'wo.emergency.created'),
   ('ita_manager', 'wo.emergency.created'),
   ('tax_manager', 'wo.emergency.created'),
   ('risk_partner', 'wo.emergency.step1_done'),
   ('admin', 'wo.emergency.deadline_near'),
   ('manager', 'wo.emergency.deadline_near'),
   ('ita_manager', 'wo.emergency.deadline_near'),
   ('tax_manager', 'wo.emergency.deadline_near'),
   ('risk_supervisor', 'wo.emergency.deadline_passed'),
   ('risk_supervisor', 'wo.risk.resubmitted'),
   ('senior_partner', 'wo.payment_plan.pending_approval'),
   ('partner', 'wo.payment_plan.pending_approval'),
   ('sqr', 'wo.payment_plan.pending_approval'),
   ('director', 'wo.payment_plan.pending_approval'),
   ('senior', 'wo.payment_plan.pending_approval'),
   ('collections_analyst', 'wo.payment_plan.pending_approval'),
   ('accounting_manager', 'wo.installment.status_changed'),
   ('accounting_analyst', 'wo.installment.status_changed'),
   ('accounting_manager', 'wo.installment.due_this_week'),
   ('accounting_analyst', 'wo.installment.due_this_week'),
   ('manager', 'wo.installment.overdue'),
   ('ita_manager', 'wo.installment.overdue'),
   ('tax_manager', 'wo.installment.overdue'),
   ('accounting_manager', 'wo.installment.overdue'),
   ('accounting_analyst', 'wo.installment.overdue'),
   ('collections_analyst', 'wo.installment.overdue'),
   ('manager', 'wo.client.billing_week'),
   ('ita_manager', 'wo.client.billing_week'),
   ('tax_manager', 'wo.client.billing_week'),
   ('manager', 'fund.request.submitted_for_approval'),
   ('ita_manager', 'fund.request.submitted_for_approval'),
   ('tax_manager', 'fund.request.submitted_for_approval'),
   ('manager', 'fund.expense.submitted_for_approval'),
   ('ita_manager', 'fund.expense.submitted_for_approval'),
   ('tax_manager', 'fund.expense.submitted_for_approval'),
   ('admin', 'fund.request.cancelled'),
   ('manager', 'fund.request.cancelled'),
   ('ita_manager', 'fund.request.cancelled'),
   ('tax_manager', 'fund.request.cancelled'),
   ('senior', 'fund.request.decided'),
   ('semisenior', 'fund.request.decided'),
   ('assistant', 'fund.request.decided'),
   ('ita_senior', 'fund.request.decided'),
   ('ita_assistant', 'fund.request.decided'),
   ('tax_senior', 'fund.request.decided'),
   ('tax_assistant', 'fund.request.decided'),
   ('accounting_analyst', 'fund.request.decided'),
   ('collections_analyst', 'fund.request.decided'),
   ('manager', 'fund.disbursement.done'),
   ('senior', 'fund.disbursement.done'),
   ('semisenior', 'fund.disbursement.done'),
   ('assistant', 'fund.disbursement.done'),
   ('ita_manager', 'fund.disbursement.done'),
   ('ita_senior', 'fund.disbursement.done'),
   ('ita_assistant', 'fund.disbursement.done'),
   ('tax_manager', 'fund.disbursement.done'),
   ('tax_senior', 'fund.disbursement.done'),
   ('tax_assistant', 'fund.disbursement.done'),
   ('manager', 'fund.settlement.recorded'),
   ('senior', 'fund.settlement.recorded'),
   ('semisenior', 'fund.settlement.recorded'),
   ('assistant', 'fund.settlement.recorded'),
   ('ita_manager', 'fund.settlement.recorded'),
   ('ita_senior', 'fund.settlement.recorded'),
   ('ita_assistant', 'fund.settlement.recorded'),
   ('tax_manager', 'fund.settlement.recorded'),
   ('tax_senior', 'fund.settlement.recorded'),
   ('tax_assistant', 'fund.settlement.recorded'),
   ('manager', 'fund.request.closed'),
   ('senior', 'fund.request.closed'),
   ('semisenior', 'fund.request.closed'),
   ('assistant', 'fund.request.closed'),
   ('ita_manager', 'fund.request.closed'),
   ('ita_senior', 'fund.request.closed'),
   ('ita_assistant', 'fund.request.closed'),
   ('tax_manager', 'fund.request.closed'),
   ('tax_senior', 'fund.request.closed'),
   ('tax_assistant', 'fund.request.closed'),
   ('senior', 'fund.expense.returned_no_support'),
   ('semisenior', 'fund.expense.returned_no_support'),
   ('assistant', 'fund.expense.returned_no_support'),
   ('ita_senior', 'fund.expense.returned_no_support'),
   ('ita_assistant', 'fund.expense.returned_no_support'),
   ('tax_senior', 'fund.expense.returned_no_support'),
   ('tax_assistant', 'fund.expense.returned_no_support'),
   ('senior', 'fund.expense.decided'),
   ('semisenior', 'fund.expense.decided'),
   ('assistant', 'fund.expense.decided'),
   ('ita_senior', 'fund.expense.decided'),
   ('ita_assistant', 'fund.expense.decided'),
   ('tax_senior', 'fund.expense.decided'),
   ('tax_assistant', 'fund.expense.decided'),
   ('senior', 'fund.expense.reviewed'),
   ('semisenior', 'fund.expense.reviewed'),
   ('assistant', 'fund.expense.reviewed'),
   ('ita_senior', 'fund.expense.reviewed'),
   ('ita_assistant', 'fund.expense.reviewed'),
   ('tax_senior', 'fund.expense.reviewed'),
   ('tax_assistant', 'fund.expense.reviewed'),
   ('manager', 'fund.expenses.all_reviewed'),
   ('ita_manager', 'fund.expenses.all_reviewed'),
   ('tax_manager', 'fund.expenses.all_reviewed'),
   ('senior', 'fund.expense.iva_penalty'),
   ('semisenior', 'fund.expense.iva_penalty'),
   ('assistant', 'fund.expense.iva_penalty'),
   ('ita_senior', 'fund.expense.iva_penalty'),
   ('ita_assistant', 'fund.expense.iva_penalty'),
   ('tax_senior', 'fund.expense.iva_penalty'),
   ('tax_assistant', 'fund.expense.iva_penalty'),
   ('accounting_manager', 'fund.expense.review_pending'),
   ('accounting_analyst', 'fund.expense.review_pending'),
   ('accounting_manager', 'fund.settlement.pending'),
   ('accounting_manager', 'fund.request.closure_pending'),
   ('accounting_manager', 'fund.disbursement.pending'),
   ('accounting_manager', 'fund.expense.sent_to_support_review'),
   ('accounting_analyst', 'fund.expense.sent_to_support_review'),
   ('accounting_manager', 'fund.expense.resubmitted'),
   ('accounting_analyst', 'fund.expense.resubmitted'),
   ('senior_partner', 'timesheet.weekly_submitted'),
   ('partner', 'timesheet.weekly_submitted'),
   ('director', 'timesheet.weekly_submitted'),
   ('manager', 'timesheet.weekly_submitted'),
   ('ita_manager', 'timesheet.weekly_submitted'),
   ('tax_manager', 'timesheet.weekly_submitted'),
   ('senior', 'timesheet.own_submit_confirmed'),
   ('semisenior', 'timesheet.own_submit_confirmed'),
   ('assistant', 'timesheet.own_submit_confirmed'),
   ('ita_senior', 'timesheet.own_submit_confirmed'),
   ('ita_assistant', 'timesheet.own_submit_confirmed'),
   ('tax_senior', 'timesheet.own_submit_confirmed'),
   ('tax_assistant', 'timesheet.own_submit_confirmed'),
   ('senior_partner', 'timesheet.team_submitted_for_approval'),
   ('partner', 'timesheet.team_submitted_for_approval'),
   ('sqr', 'timesheet.team_submitted_for_approval'),
   ('director', 'timesheet.team_submitted_for_approval'),
   ('manager', 'timesheet.team_submitted_for_approval'),
   ('senior', 'timesheet.team_submitted_for_approval'),
   ('ita_manager', 'timesheet.team_submitted_for_approval'),
   ('tax_manager', 'timesheet.team_submitted_for_approval'),
   ('it_security_manager', 'timesheet.overdue'),
   ('senior_partner', 'timesheet.overdue'),
   ('partner', 'timesheet.overdue'),
   ('sqr', 'timesheet.overdue'),
   ('director', 'timesheet.overdue'),
   ('manager', 'timesheet.overdue'),
   ('senior', 'timesheet.overdue'),
   ('semisenior', 'timesheet.overdue'),
   ('assistant', 'timesheet.overdue'),
   ('ita_manager', 'timesheet.overdue'),
   ('ita_senior', 'timesheet.overdue'),
   ('ita_assistant', 'timesheet.overdue'),
   ('tax_manager', 'timesheet.overdue'),
   ('tax_senior', 'timesheet.overdue'),
   ('tax_assistant', 'timesheet.overdue'),
   ('risk_partner', 'timesheet.overdue'),
   ('it_security_manager', 'timesheet.reverted'),
   ('senior_partner', 'timesheet.reverted'),
   ('partner', 'timesheet.reverted'),
   ('sqr', 'timesheet.reverted'),
   ('director', 'timesheet.reverted'),
   ('manager', 'timesheet.reverted'),
   ('senior', 'timesheet.reverted'),
   ('semisenior', 'timesheet.reverted'),
   ('assistant', 'timesheet.reverted'),
   ('ita_manager', 'timesheet.reverted'),
   ('ita_senior', 'timesheet.reverted'),
   ('ita_assistant', 'timesheet.reverted'),
   ('tax_manager', 'timesheet.reverted'),
   ('tax_senior', 'timesheet.reverted'),
   ('tax_assistant', 'timesheet.reverted'),
   ('risk_partner', 'timesheet.reverted'),
   ('it_security_manager', 'timesheet.pending_approval'),
   ('senior_partner', 'timesheet.pending_approval'),
   ('partner', 'timesheet.pending_approval'),
   ('sqr', 'timesheet.pending_approval'),
   ('director', 'timesheet.pending_approval'),
   ('manager', 'timesheet.pending_approval'),
   ('senior', 'timesheet.pending_approval'),
   ('semisenior', 'timesheet.pending_approval'),
   ('assistant', 'timesheet.pending_approval'),
   ('ita_manager', 'timesheet.pending_approval'),
   ('ita_senior', 'timesheet.pending_approval'),
   ('ita_assistant', 'timesheet.pending_approval'),
   ('tax_manager', 'timesheet.pending_approval'),
   ('tax_senior', 'timesheet.pending_approval'),
   ('tax_assistant', 'timesheet.pending_approval'),
   ('risk_partner', 'timesheet.pending_approval'),
   ('senior', 'tracker.timer.auto_stopped'),
   ('semisenior', 'tracker.timer.auto_stopped'),
   ('assistant', 'tracker.timer.auto_stopped'),
   ('ita_senior', 'tracker.timer.auto_stopped'),
   ('ita_assistant', 'tracker.timer.auto_stopped'),
   ('tax_senior', 'tracker.timer.auto_stopped'),
   ('tax_assistant', 'tracker.timer.auto_stopped'),
   ('senior', 'approval.line_approved'),
   ('semisenior', 'approval.line_approved'),
   ('assistant', 'approval.line_approved'),
   ('ita_senior', 'approval.line_approved'),
   ('ita_assistant', 'approval.line_approved'),
   ('tax_senior', 'approval.line_approved'),
   ('tax_assistant', 'approval.line_approved'),
   ('senior', 'approval.line_rejected'),
   ('semisenior', 'approval.line_rejected'),
   ('assistant', 'approval.line_rejected'),
   ('ita_senior', 'approval.line_rejected'),
   ('ita_assistant', 'approval.line_rejected'),
   ('tax_senior', 'approval.line_rejected'),
   ('tax_assistant', 'approval.line_rejected'),
   ('senior', 'approval.revision_requested'),
   ('semisenior', 'approval.revision_requested'),
   ('assistant', 'approval.revision_requested'),
   ('ita_senior', 'approval.revision_requested'),
   ('ita_assistant', 'approval.revision_requested'),
   ('tax_senior', 'approval.revision_requested'),
   ('tax_assistant', 'approval.revision_requested'),
   ('admin', 'approval.training_pending'),
   ('hr_manager', 'approval.training_pending'),
   ('hr_analyst', 'approval.training_pending'),
   ('manager', 'engagement.rejected_by_partner'),
   ('ita_manager', 'engagement.rejected_by_partner'),
   ('tax_manager', 'engagement.rejected_by_partner'),
   ('manager', 'engagement.pending_partner_approval'),
   ('ita_manager', 'engagement.pending_partner_approval'),
   ('tax_manager', 'engagement.pending_partner_approval'),
   ('admin', 'scheduler.coverage_gap'),
   ('senior_partner', 'scheduler.coverage_gap'),
   ('partner', 'scheduler.coverage_gap'),
   ('sqr', 'scheduler.coverage_gap'),
   ('director', 'scheduler.coverage_gap'),
   ('manager', 'scheduler.coverage_gap'),
   ('senior', 'scheduler.coverage_gap'),
   ('ita_manager', 'scheduler.coverage_gap'),
   ('tax_manager', 'scheduler.coverage_gap'),
   ('senior', 'scheduler.own_assignment_changed'),
   ('semisenior', 'scheduler.own_assignment_changed'),
   ('assistant', 'scheduler.own_assignment_changed'),
   ('ita_senior', 'scheduler.own_assignment_changed'),
   ('ita_assistant', 'scheduler.own_assignment_changed'),
   ('tax_senior', 'scheduler.own_assignment_changed'),
   ('tax_assistant', 'scheduler.own_assignment_changed'),
   ('it_security_manager', 'timesheet.reminder.daily'),
   ('senior_partner', 'timesheet.reminder.daily'),
   ('partner', 'timesheet.reminder.daily'),
   ('sqr', 'timesheet.reminder.daily'),
   ('director', 'timesheet.reminder.daily'),
   ('manager', 'timesheet.reminder.daily'),
   ('senior', 'timesheet.reminder.daily'),
   ('semisenior', 'timesheet.reminder.daily'),
   ('assistant', 'timesheet.reminder.daily'),
   ('ita_manager', 'timesheet.reminder.daily'),
   ('ita_senior', 'timesheet.reminder.daily'),
   ('ita_assistant', 'timesheet.reminder.daily'),
   ('tax_manager', 'timesheet.reminder.daily'),
   ('tax_senior', 'timesheet.reminder.daily'),
   ('tax_assistant', 'timesheet.reminder.daily'),
   ('risk_partner', 'timesheet.reminder.daily'),
   ('admin', 'approval.reminder.weekly'),
   ('it_security_manager', 'approval.reminder.weekly'),
   ('senior_partner', 'approval.reminder.weekly'),
   ('partner', 'approval.reminder.weekly'),
   ('sqr', 'approval.reminder.weekly'),
   ('director', 'approval.reminder.weekly'),
   ('manager', 'approval.reminder.weekly'),
   ('senior', 'approval.reminder.weekly'),
   ('semisenior', 'approval.reminder.weekly'),
   ('assistant', 'approval.reminder.weekly'),
   ('ita_manager', 'approval.reminder.weekly'),
   ('ita_senior', 'approval.reminder.weekly'),
   ('ita_assistant', 'approval.reminder.weekly'),
   ('tax_manager', 'approval.reminder.weekly'),
   ('tax_senior', 'approval.reminder.weekly'),
   ('tax_assistant', 'approval.reminder.weekly'),
   ('risk_partner', 'approval.reminder.weekly'),
   ('hr_manager', 'approval.reminder.weekly'),
   ('hr_analyst', 'approval.reminder.weekly'),
   ('accounting_manager', 'fund.reminder.weekly'),
   ('accounting_analyst', 'fund.reminder.weekly'),
   ('manager', 'wo.installment.reminder.weekly'),
   ('ita_manager', 'wo.installment.reminder.weekly'),
   ('tax_manager', 'wo.installment.reminder.weekly'),
   ('accounting_manager', 'wo.installment.reminder.weekly'),
   ('accounting_analyst', 'wo.installment.reminder.weekly'),
   ('collections_analyst', 'wo.installment.reminder.weekly')
 );
delete from public.notification_types
 where type_key not in (
   'auth.account.email',
   'auth.user.registered',
   'auth.role.changed',
   'auth.account.blocked',
   'auth.account.deleted',
   'staff.created',
   'staff.terminated',
   'staff.competency.assigned',
   'staff.competency.removed',
   'client.created',
   'client.updated',
   'client.deactivated',
   'engagement.created',
   'engagement.owners.changed',
   'engagement.ending_soon',
   'engagement.finalized',
   'engagement.deleted',
   'engagement.sqr_assigned',
   'engagement.encargado_assigned',
   'engagement.specialist_assigned',
   'engagement.staffing.changed',
   'worksheet.sent_to_quality',
   'wo.submitted_partner',
   'wo.submitted_risk',
   'wo.approved_partner',
   'wo.rejected_partner',
   'wo.approved_risk',
   'wo.rejected_risk',
   'wo.approval_reverted',
   'wo.emergency.created',
   'wo.emergency.step1_done',
   'wo.emergency.deadline_near',
   'wo.emergency.deadline_passed',
   'wo.risk.resubmitted',
   'wo.payment_plan.pending_approval',
   'wo.installment.status_changed',
   'wo.installment.due_this_week',
   'wo.installment.overdue',
   'wo.client.billing_week',
   'fund.request.submitted_for_approval',
   'fund.expense.submitted_for_approval',
   'fund.request.cancelled',
   'fund.request.decided',
   'fund.disbursement.done',
   'fund.settlement.recorded',
   'fund.request.closed',
   'fund.expense.returned_no_support',
   'fund.expense.decided',
   'fund.expense.reviewed',
   'fund.expenses.all_reviewed',
   'fund.expense.iva_penalty',
   'fund.expense.review_pending',
   'fund.settlement.pending',
   'fund.request.closure_pending',
   'fund.disbursement.pending',
   'fund.expense.sent_to_support_review',
   'fund.expense.resubmitted',
   'timesheet.weekly_submitted',
   'timesheet.own_submit_confirmed',
   'timesheet.team_submitted_for_approval',
   'timesheet.overdue',
   'timesheet.reverted',
   'timesheet.pending_approval',
   'tracker.timer.auto_stopped',
   'approval.line_approved',
   'approval.line_rejected',
   'approval.revision_requested',
   'approval.training_pending',
   'engagement.rejected_by_partner',
   'engagement.pending_partner_approval',
   'scheduler.coverage_gap',
   'scheduler.own_assignment_changed',
   'timesheet.reminder.daily',
   'approval.reminder.weekly',
   'fund.reminder.weekly',
   'wo.installment.reminder.weekly'
 );
