/**
 * Companion types for skills + staff_skills tables.
 *
 * Mirrors the Supabase auto-generated Row/Insert/Update pattern.
 * Once types.ts is regenerated by Lovable Cloud, migrate imports to
 * Database["public"]["Tables"]["skills"]["Row"] etc.
 */

// ── skills ────────────────────────────────────────────────────

export type SkillRow = {
  skill_id: string
  name: string
  category: string
  is_active: boolean | null
  created_at: string | null
  updated_at: string | null
}

export type SkillInsert = {
  skill_id?: string
  name: string
  category: string
  is_active?: boolean | null
  created_at?: string | null
  updated_at?: string | null
}

export type SkillUpdate = {
  skill_id?: string
  name?: string
  category?: string
  is_active?: boolean | null
  created_at?: string | null
  updated_at?: string | null
}

// ── staff_skills ──────────────────────────────────────────────

export type StaffSkillRow = {
  staff_skill_id: string
  staff_id: string
  skill_id: string
  proficiency_level: string
  last_evaluated_date: string | null
  created_at: string | null
  updated_at: string | null
}

export type StaffSkillInsert = {
  staff_skill_id?: string
  staff_id: string
  skill_id: string
  proficiency_level: string
  last_evaluated_date?: string | null
  created_at?: string | null
  updated_at?: string | null
}

export type StaffSkillUpdate = {
  staff_skill_id?: string
  staff_id?: string
  skill_id?: string
  proficiency_level?: string
  last_evaluated_date?: string | null
  created_at?: string | null
  updated_at?: string | null
}

// ── Proficiency level constants ───────────────────────────────

export const PROFICIENCY_LEVELS = ['Beginner', 'Intermediate', 'Advanced'] as const
export type ProficiencyLevel = typeof PROFICIENCY_LEVELS[number]

// ── Skill category constants ──────────────────────────────────

export const SKILL_CATEGORIES = [
  'framework',
  'industry',
  'tool',
  'language',
  'certification',
  'other',
] as const
export type SkillCategory = typeof SKILL_CATEGORIES[number]
